### ISSUE TITLE
Briefcase dev error on Linux Mint

### ISSUE THREAD

**Issue by ebuka-odih** [beeware/briefcase#524] opened 2020-11-06 22:41 UTC
OS: LInux Mint
Python V: Python3.7
Pip V: pip-20.2.4

i am just installing Beeware for the first time, after all the necessary installations i tried to run briefcase dev then i got this error

`[helloworld] Installing dependencies...
Collecting toga-gtk>=0.3.0.dev20
  Using cached toga_gtk-0.3.0.dev25-py3-none-any.whl (41 kB)
Processing /home/emma/.cache/pip/wheels/dc/f1/a5/bc0af60e544c2e6564fe9a3a6d8bb6351e207a092516bdba00/pycairo-1.20.0-cp37-cp37m-linux_x86_64.whl
Collecting pygobject>=3.14.0
  Using cached PyGObject-3.38.0.tar.gz (712 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting toga-core==0.3.0.dev25
  Using cached toga_core-0.3.0.dev25-py3-none-any.whl (484 kB)
Processing /home/emma/.cache/pip/wheels/87/6b/e0/644893b70bd461b82668f01d155242370260610cb1722d810e/gbulb-0.6.1-py3-none-any.whl
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /home/emma/anaconda3/lib/python3.7/site-packages (from toga-core==0.3.0.dev25->toga-gtk>=0.3.0.dev20) (1.3.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /home/emma/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->toga-core==0.3.0.dev25->toga-gtk>=0.3.0.dev20) (0.6.0)
Requirement already satisfied, skipping upgrade: more-itertools in /home/emma/anaconda3/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->toga-core==0.3.0.dev25->toga-gtk>=0.3.0.dev20) (8.0.2)
Building wheels for collected packages: pygobject
  Building wheel for pygobject (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/emma/anaconda3/bin/python3.7 /home/emma/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmprtt9q27k
       cwd: /tmp/pip-install-2xwiiz6j/pygobject
  Complete output (90 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.7/pygtkcompat
  creating build/lib.linux-x86_64-3.7/gi
  copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/module.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_error.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/types.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_option.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/importer.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.7/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-3.7/gi
  creating build/lib.linux-x86_64-3.7/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.7/gi/repository
  creating build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.7/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.7/gi/overrides
  running build_ext
  pycairo: new API
  Traceback (most recent call last):
    File "/home/emma/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/emma/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/emma/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 217, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 1259, in <module>
      main()
    File "setup.py", line 1254, in main
      zip_safe=False,
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/emma/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/emma/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/emma/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/home/emma/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/emma/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/emma/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/emma/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/emma/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 1088, in run
      self._setup_extensions()
    File "setup.py", line 1083, in _setup_extensions
      add_pycairo(gi_cairo_ext)
    File "setup.py", line 1066, in add_pycairo
      ext.include_dirs += [get_pycairo_include_dir()]
    File "setup.py", line 893, in get_pycairo_include_dir
      include_dir = find_path(find_new_api())
    File "setup.py", line 848, in find_new_api
      import cairo
    File "/tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
      from ._cairo import *  # noqa: F401,F403
  ImportError: /tmp/pip-build-env-j9cau_27/overlay/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
  ----------------------------------------
  ERROR: Failed building wheel for pygobject
Failed to build pygobject
ERROR: Could not build wheels for pygobject which use PEP 517 and cannot be installed directly
Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server`

**Comment by freakboy3742** [comment] 2020-11-08 23:23
Thanks for the report; this appears to be a duplicate of #526 (which was originally reported against the beeware/beeware repository).

**Closed by freakboy3742** 2020-11-08 23:23 UTC
Labels: bug, duplicate
