### ISSUE TITLE
Builded Linux AppImage files by Briefcase are not working with glib2 2.70

### ISSUE THREAD

**Issue by zili55** [beeware/briefcase#631] opened 2021-10-22 21:17 UTC
**Describe the bug**
With glib2 library version 2.70 builded Linux AppImage files are not working. Here is the error:
```
>>> /home/criaz/repos/briefcase-613/hello/linux/hello-0.0.1-x86_64.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_hello-9Pm4Um/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_hello-9Pm4Um/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_hello-9Pm4Um/usr/app/hello/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_hello-9Pm4Um/usr/app/hello/app.py", line 27, in main
    return hello()
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/toga/app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/toga_gtk/app.py", line 8, in <module>
    import gbulb
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/gbulb/__init__.py", line 1, in <module>
    from .glib_events import *
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/gbulb/glib_events.py", line 12, in <module>
    from gi.repository import GLib, Gio
  File "/tmp/.mount_hello-9Pm4Um/usr/app_packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```
New glib2 comes with the new system update and lot of people are complaining about that many AppImage files are stopped working.

**To Reproduce**
```
briefcase new
briefcase create
briefcase run -u
```
or just execute the `AppImage` file made by Briefcase.

**Expected behavior**
Appimage files shouldn't fail.

**Environment:**
 - Operating System: Manjaro Linux 21.1.6
 - Python version: Python 3.9.0
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.2.15

**Comment by freakboy3742** [comment] 2021-10-23 00:38
Good to know there's a temporary workaround, but... that's not going to be a long term solution :-)

To confirm what is going on here: are you building using Docker, or natively using Arch? If you're building in Docker, this suggests that we're missing a system dependency when we're building the AppImage. The AppImage should only be dependent on the C library, and nothing else; everything else the app needs should be bundled with the app. 

If the dependency is missing in the AppImage, but there's something on the user's system that satisfies the requirement, then the app may still work - but then when the user *doesn't* have the requirement, the app will fail. 

So: the question to answer here: Why isn't glib2 from Ubuntu 18.04 *not* being included in the AppImage?

**Comment by freakboy3742** [comment] 2021-10-24 01:13
That's my understanding of how AppImage works, yes - it packages *all* the SO files that aren't "core system" DLLs. I thought that include GLib/GTK; but my understanding may be incorrect.

**Comment by zili55** [comment] 2021-11-03 08:25
Yes, but some shared libraries are blacklisted [link](https://github.com/AppImage/pkg2appimage/blob/master/excludelist), `libgio-2.0.so.0` is included in that list. That is the reason why we see this when we build appimage:
```
Skipping deployment of blacklisted library /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 
```
So when we run a builded appimage, then it tries to use system libgio-2.0.so.0, and in my case it fails because I upgraded glib2 on my system.

I tried the following approaches so far:
- tried to run linuxdeploy to include libgio-2.0.so.0 (with `--library` option) from Ubuntu 18.04, but when I run appimage then it fails on different [error](https://pastebin.com/Uh4Auwm8)
- I copied `libgio-2.0.so.0` from and older glib2 aka `glib2-2.68.4-1-x86_64.pkg.tar.zst` to `hello/linux/appimage/hello/hello.AppDir/usr/lib`, this way build is successful and I can execute the appimage without any problem

Do you have any recommendation how should I continue @freakboy3742 ?

**Comment by freakboy3742** [comment] 2021-11-03 10:34
@zili55 Honestly - my suggestion at this point is to take it up with the AppImage folks. They're explicitly excluding an SO file for a reason; that reason apparently causes problems with Arch. At this point, they're the people to ask what the "right" solution is.

**Comment by zili55** [comment] 2021-11-04 20:33
I found a linuxdeploy [plugin](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk) (it's an experimental plugin) which job is to bundle additional resources for applications that use GTK, libgio is included also for example. This way builded appimage works on my Arch based distro. 

`--plugin gtk` opt needs to be added to linuxdeploy command, and also the following three package to `pyproject.toml`:
 - patchelf
 - libgtk-3-dev
 - librsvg2-dev 
These packages are needed by that gtk plugin, and plugin needs to be downloaded to `~/.briefcase/tools` as well.

**Comment by freakboy3742** [comment] 2021-11-19 23:53
@zili55 The word "Experimental" doesn't fill me with enthusiasm, but if it's needed, then I guess it's the best option.

More broadly, I guess I'm trying to get a feel for what the plugin is doing. Is the GTK plugin the only plugin that will ever be needed, or will other apps need other plugins? Essentially, I'm trying to work out if this is a case of adding one tool, or if we need to add a general configuration endpoint to let users define the the AppImage plugins that they want to use, with the default Toga/GTK template specifying the GTK plugin.

**Comment by leggewie** [comment] 2022-02-16 22:12
https://github.com/AppImage/AppImageKit/issues/1162

**Comment by leggewie** [comment] 2022-02-17 10:28
So, it looks like there are at least two workarounds for the issue with the undefined symbol g_module_open_full by repacking the squashfs-root:

1. `rm -Rvf squashfs-root/usr/lib/libgmodule*` as suggested [here](https://github.com/project-slippi/Ishiiruka/issues/323#issuecomment-977415376) and [upstream](https://github.com/AppImage/AppImageKit/issues/1162#issuecomment-997213699) from AppImageKit
2. inject and replace some glib2 files with older versions as suggested [here in this ticket](https://github.com/beeware/briefcase/issues/631#issuecomment-949971419) and [here](https://bbs.archlinux.org/viewtopic.php?id=269838).

I can confirm that both "work" to the extent that the error about g_module_open_full no longer stops the execution of the AppImage.  The second workaround subsequently gives me problems with a missing libpcre.so.1 library (that stuff must be ancient).  Linking libpcre.so.3 to libpcre.so.1 as suggested [elsewhere](https://programmerah.com/linux-ubuntu-django-error-uwsgi-error-while-loading-shared-libraries-libpcre-so-1-41007/) did not fix that issue.

    $ ldd squashfs-root/usr/lib/libglib-2.0.so.0.6800.4|grep not
    libpcre.so.1 => not found`

I conclude that simply removing the libgmodule files is preferable and blessed by upstream.  Can this be automated/be made permanent so that we don't have to manully repack the AppImage every time?

**Comment by freakboy3742** [comment] 2022-02-28 05:08
@leggewie It's certainly possible to automate - we can add anything we want to the `build` command in the Briefcase AppImage backend. 

Since this seems like it might be a generic class of problem, it might be worth adding this as a configurable item in the Linux configuration file. Rather than hacking in a specific fix for libgmodule, we could expose to the user a list of "items to purge from the image". In that way, it will be configurable (if other libraries cause this problem in the future), so we won't need to cut a full Briefcase release to add another file to the list - just publish a new version of the Linux template.

**Comment by freakboy3742** [comment] 2022-04-22 02:25
I'm going to close this issue to consolidate the general problem of "Linux AppImage deployment has problems" under a single issue (#718).

**Closed by freakboy3742** 2022-04-22 02:25 UTC
Labels: bug, up-for-grabs, linux
