### ISSUE TITLE
BRIEFCASE RUN COMMAND NOT WORKING ON WINDOWS

### ISSUE THREAD

**Issue by adetobi22** [beeware/briefcase#732] opened 2022-05-05 13:48 UTC
Briefcase run command not working, unable to start app.
I have listed the required dependencies in the pyproject.toml ( in my case it's just httpx) , i ran update update -d and build again. but the run command still doesn't work , it keeps displaying " unable to start app. I'm using Windows. still running the tutorial. it starts using briefcase dev but briefcase run doesn't work, briefcase run android still works well but it's not updated. the only dependency that needs to update was httpx. I opened another program "hellobeeware" to see if it was the formal "helloworld program that has the problem, but the new "hellobeeware program still has thesame problem

**Comment by freakboy3742** [comment] 2022-05-05 22:07
Closing because the investigation on #729 hasn't concluded, and we haven't yet determined whether the problem is user error.

**Closed by freakboy3742** 2022-05-05 22:07 UTC
