### ISSUE TITLE
  Requested 'cairo >= 1.15.10' but version of cairo is 1.14.6     Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by istiakahmad** [beeware/briefcase#526] opened 2020-11-08 11:50 UTC
**Describe the bug**
System: Ubuntu 18.04
"briefcase dev" command run successfully but when I try to run "briefcase create" on my system, I face this issue. In my system, I install cairo 1.15.10 and there is no version for cairo 1.14.6.

**This error message is shown:**
```
Downloading PyGObject-3.38.0.tar.gz (712 kB)
     |################################| 712 kB 2.7 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8hregxrd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo
       cwd: None
  Complete output (36 lines):
  WARNING: The directory '/home/brutus/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  Collecting setuptools
    Downloading setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Downloading wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting pycairo
    Downloading pycairo-1.20.0.tar.gz (344 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: pycairo
    Building wheel for pycairo (PEP 517): started
    Building wheel for pycairo (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpa4kjkl9u
         cwd: /tmp/pip-install-e5fj61pu/pycairo
    Complete output (12 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.6/cairo
    running build_ext
    Requested 'cairo >= 1.15.10' but version of cairo is 1.14.6
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
    ----------------------------------------
    ERROR: Failed building wheel for pycairo
  Failed to build pycairo
  ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8hregxrd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo Check the logs for full command output.
```
after running this command:   pkg-config --modversion cairo
1.15.10

**Comment by geogriff** [comment] 2020-11-09 22:06
For reference, pycairo started requiring cairo-1.15.10 in [f72fb39](https://github.com/pygobject/pycairo/commit/f72fb39debdc8a3daafb8f7a6721b1010dd7c0d1) which seems to first shipped in pycairo-1.20.0.

**Comment by n3bojs4** [comment] 2020-11-09 23:15
> Thanks for the report. We've seen this bug reported on Gitter, but we had neglected to write up a formal bug report.
> 
> The issue appears to be that PyCairo (or something in it's chain of dependencies) has published an update since we initially got Linux packaging working; however, that update is no longer compatible with the version of Cairo that is available on Ubuntu 16.04. It should be possible to pin the versions to resolve this issue; however, we need to diagnose which versions need pinning.

Hello, is there a workaround to continue the tutorial ?
Thanks for your work :)

**Comment by bmeares** [comment] 2020-11-10 04:48
@n3bojs4 I haven't been able to find a workaround at the moment, but in case you'd like to continue the tutorial, builds for other platforms seem to work correctly, such as building for Android. Hoping the version gets pinned soon or maybe a Docker image built on `manylinux` can help resolve this and future issues (mentioned in [this issue](https://github.com/beeware/Python-Linux-support/issues/2)).

**Comment by n3bojs4** [comment] 2020-11-10 06:24
@bmeares thanks for the reply, I already did it. I landed on this project looking if it was possible to develop python applications for Android. My emulator seems to be very slow....

**Comment by geogriff** [comment] 2020-11-13 18:08
Here's a summary of the chain of issues that lead to this breakage. Fixing or working around any one of these issues would break the chain and fix the build:
1. pygobject requires pycairo as a build dependency in its pyproject.toml, with pycairo version unbounded.
2. pycairo-1.20.0 bumped their libcairo version requirement to >=1.15.10 in commit [f72fb39](https://github.com/pygobject/pycairo/commit/f72fb39debdc8a3daafb8f7a6721b1010dd7c0d1) with the comment: "We now require Python 3.6 and nearly all distros shipping 3.6+ also have cairo 1.15.10+."
3. briefcase linux build uses ubuntu xenial, which only ships cairo 1.13.x and python up to 3.5, but briefcase uses a ppa to install python3.6+.
4. pinning pycairo to <1.20.0 in a briefcase project's pyproject.toml does not work because pip installs build dependencies (in this case, of pygobject) in an [isolated environment](https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support), ignoring version requirements of the dependent project.

To me, issue # 3 stands out as a root cause, since briefcase is building in a non-standard environment (xenial with a custom ppa for python>=3.6).

The workaround which works for me is to run briefcase with python3.5 (by e.g. running it in ubuntu xenial or debian stretch) which forces pip to ignore any version of pycairo which requires python3.6, thus avoiding any version of pycairo which requires libcairo >= 1.15 (see issue # 2 listed above).

**Comment by danyeaw** [comment] 2020-11-13 18:52
Support for Ubuntu 16.04 will end in 5 months, I agree that updating Briefcase to use a newer (latest?) LTS would be an ideal solution.

**Comment by freakboy3742** [comment] 2020-11-14 02:02
Ok - that's not *entirely* true - 16.04 will be [maintained until 2024](https://ubuntu.com/about/release-cycle); however, it will only receive security updates. 

However, since supporting 16.04 is causing headaches, and we haven't got a huge community of active Linux users offering to maintain 16.04 support, I'd agree that moving to 18.04 as a baseline is our best option here.

This has the added benefit that we can drop Python 3.5 support at the same time - Py3.5 is unsupported by Python, and Ubuntu 16.04 was the last reason to maintain that support.

If someone wanted to try their hand at a patch, this *should* be as simple as bumping the Dockerfile base image, and tweaking the `system_packages` definition to match 18.04 requirements...

**Comment by freakboy3742** [comment] 2020-11-21 02:28
Since this error keeps being reported on Gitter, I've made the changes, and migrated the Linux support package and template to use Ubuntu 18.04 as the base image. From my testing, the tutorial now builds without any problems, so I'm going to close this ticket.

**Closed by freakboy3742** 2020-11-21 02:28 UTC
