### ISSUE TITLE
AppImage loads Python code from project's sources, not from inside of AppImage

### ISSUE THREAD

**Issue by jhakonen** [beeware/briefcase#662] opened 2022-01-28 18:16 UTC
**Describe the bug**
Running built AppImage loads Python sources from source tree instead of loading them from inside of the AppImage. This appears to happen when project's Python package is at project's root, and not in `src` folder. 

You may get this abnormal folder structure if you create your project as Poetry project (with `poetry new`) and later on migrate to Briefcase.

**To Reproduce**
1. Create new Toga project using default answers with:
```bash
briefcase new
cd helloworld
```
2. Move `helloworld` package to root level:
```bash
mv src/helloworld .
rmdir src
sed -i 's|src/helloworld|helloworld|' pyproject.toml
```
3. Then build AppImage:
```bash
briefcase build
```
4. Run the built AppImage:
```bash
linux/Hello_World-0.0.1-x86_64.AppImage
```
5. You should see this:
![helloworld](https://user-images.githubusercontent.com/1950698/151598132-9881fc3b-10e9-4ce0-82bd-6a8bf843c341.png)
6. Next in `helloworld/app.py` change window title from:
```python
self.main_window = toga.MainWindow(title=self.formal_name)
```
To:
```python
self.main_window = toga.MainWindow(title='You cannot see me!')
```
7. Finally run the AppImage again. Do not build it, just run the previously built AppImage:
```bash
linux/Hello_World-0.0.1-x86_64.AppImage
```
8. The title has changed, even though it shouldn't have:
![changed-title](https://user-images.githubusercontent.com/1950698/151598763-88432791-d126-40a6-b1ea-5f73df2c5b66.png)

**Expected behavior**
The title should have remained as "Hello World" as I didn't rebuild the AppImage.

**Environment:**
 - Operating System: Pop!_OS 20.04
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30

**Additional context**
This bug appears to depend on current working directory. If you cd to parent directory then the AppImage will load its sources correctly from inside of it:
```bash
cd ..
helloworld/linux/Hello_World-0.0.1-x86_64.AppImage
```

**Comment by freakboy3742** [comment] 2022-01-29 01:30
That's *very* weird.... thanks for the report.

The last bit of Additional Context is essentially the explanation of what is going on.

A python interpreter, by default, has the current working directory as the first entry on the PYTHONPATH. When you have a `helloworld` module folder in the current working directory, that folder is taking priority over the one that is in the AppImage bundle. This is a manifestation of the main reason why `src` folders are desirable in project layouts. 

However, it's also a bug lying in wait - because if an end user ever had a Python module named `helloworld` in their current working directory, the AppImage won't start. Following on from your example:
```
mkdir somewhere
cd somewhere
mkdir helloworld
touch helloworld/__init__.py
../helloworld/linux/Hello_World-0.0.1-x86_64.AppImage
```
will crash, because the "new" helloworld module takes priority over the one in the app.

So - the root of the problem is that we need to configure the AppImage so that the startup script *doesn't* include the current working directory in the PYTHONPATH.

This is something that *might* be fixed by #628 - or, at least, it gives us a little more control over the interpreter startup process, which we could use to address this problem.

**Closed** 2022-07-30 04:10 UTC
Labels: bug, up-for-grabs, linux
