### ISSUE TITLE
initial android app getting crash

### ISSUE THREAD

**Issue by sulabh9999** [beeware/briefcase#454] opened 2020-07-16 15:47 UTC
**Describe the bug**
In current version(0.3.2) first android app(just after installation) is getting crash.

**To Reproduce**
1. `briefcase build android`
2. `adb install myapp.apk`
after launching app
3. `adb logcat AndroidRuntime:E *:s`
 
```
07-16 20:49:42.564  1279  1279 E AndroidRuntime: FATAL EXCEPTION: main
07-16 20:49:42.564  1279  1279 E AndroidRuntime: Process: com.udp.TestUDP, PID: 1279
07-16 20:49:42.564  1279  1279 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.udp.TestUDP/org.beeware.android.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.beeware.android.IPythonApp.onCreate()' on a null object reference
07-16 20:49:42.564  1279  1279 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
07-16 20:49:42.564  1279  1279 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
07-16 20:49:42.564  1279  1279 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
07-16 20:49:42.564  1279  1279 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-16 20:49:42.564  1279  1279 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
...
```

**Comment by freakboy3742** [comment] 2020-07-16 22:14
Can you share more details about what you're doing, like the device you're using, the app you're building, and so on? The error you're reporting suggests either the app hasn't been built correctly, or it's an empty app.

**Comment by sulabh9999** [comment] 2020-07-18 16:04
It's an default(empty) app which created by beeware is setup first time, without single line of code modification. I'm able to install app but getting crash just after launch. My device details are:-
OS: ubuntu 18.04
phone: Android 9
python: 3.6
pip3

**Comment by freakboy3742** [comment] 2020-07-18 22:42
When you generated the app, did you select "Toga" as the GUI framework, or something else? Does the code in `app.py` match [what the tutorial says you should get](https://docs.beeware.org/en/latest/tutorial/tutorial-2.html#what-was-generated)?

**Comment by Garrapata-Piletera** [comment] 2020-07-23 04:00
Hi, I'm having the same issue, with the same exceptions from the debugger. I did some digging and I think I've found a clue.

I tried it in a clean venv and it made no difference and I tried in a physical device as well. The app crashes all the same in those scenarios. I used Toga GUI and the `app.py` matches what the tutorial says. When I run `briefcase run android` on the default `helloworld` project, it installs the app fine, it shows the "Made with Beeware" splash screen, but then it crashes.

The debugger seem to suggest the culprit is the function `run_forever_cooperatively()` from the class `AndroidEventLoop` (line 26 from the pastebin), specifically, it seems to be a problem with the call to `_set_coroutine_origin_tracking(self._debug)`. Something is not happy with that call.

https://pastebin.com/jaXaeTV8 (part of emulator debug report)

I'm not savvy enough to help further, I'm adding the steps I followed below. If you can point me to how can I do some more digging (or you need any more info) I'll be glad to provide it.

¡Thank you freakboy!

**To reproduce**
1. `briefcase new`
2. Accept all defaults for helloworld project
3. `briefcase create android`
4. `briefcase build android`
5. `briefcase run android -d @beePhone`
6. Emulator starts. App installs and opens
7. App crashes after splash screen


**Some box details**
- OS: Ubuntu 18.04.4 LTS

In the virtual environment I have:
- Python 3.6.9
- pip 20.0.1
- briefcase 0.3.3

**Comment by freakboy3742** [comment] 2020-07-24 00:23
Thanks for that log - it looks like the problem is an incompatibility with Python 3.6. We're referencing a method (`_set_coroutine_origin_tracking`) that didn't exist in Python 3.6's asyncio implementation. 

As an immediate workaround, updating to Python 3.7 will fix this.

**Comment by freakboy3742** [comment] 2020-07-26 23:19
This should now be resolved by the release of Rubicon v0.2.3.

**Closed by freakboy3742** 2020-07-26 23:19 UTC
Labels: bug

**Comment by czoins** [comment] 2020-11-24 01:57
I still have the same issue.

**Comment by devinprater** [comment] 2021-04-17 00:23
I have the same issue as well.
