### ISSUE TITLE
IOS app refuses to open

### ISSUE THREAD

**Issue by Morgandri1** [beeware/briefcase#702] opened 2022-04-08 05:03 UTC
**Describe the bug**
using the hello world tutorial, I used my personal iPhone as the simulator. when i opened the app however, i was left with a white screen.

**To Reproduce**
1. Go to xcode
2. Click on 'signing and capabilities' 
3. click on 'app name' > device name
4. hit the "run" button
5. when the app installs, open it. nothing will happen

**Expected behavior**
this should make the app open and perform as it does in the ios simulator 

**Screenshots**
N/A, a white screen is all you see on the device side. hard to tell if Xcode is passing an error though. doesnt seem to be.

(although, when running, main.m opens up and 'Thread 1: EXC_BAD_ACCESS (code=2, address=0x107f23e08)' is shown)

**Environment:**
 - Operating System: MacOS monterey 12.3
 - Python version: 3.9.8
 - Software versions: IOS 14.6 (not working), IOS simulator 14.5 and 15.4 (both working)
   - Briefcase: 0.3.6
   - Toga: 0.2.15
   - Xcode: 13.3

**Comment by freakboy3742** [comment] 2022-04-11 05:18
Thanks for the report. Unfortunately, you've hit a [known bug when running on physical devices](https://github.com/beeware/Python-Apple-support/issues/131). Running in the simulator works; the issue is only on physical devices. The problem doesn't exist for Python 3.7, and you can work around the problem for Python 3.8 by specifying an older support library; however, recent 3.8 builds and all 3.9+ builds are affected.
 
I'm going to close this issue as the underlying problem is known, but doesn't lie in Briefcase itself; follow the issue on the Python-Apple-support repository for updates.

**Closed by freakboy3742** 2022-04-11 05:18 UTC
Labels: bug
