### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810 (on mac sierra)

### ISSUE THREAD

**Issue by itsjesseyo** [beeware/briefcase#66] opened 2017-08-18 02:30 UTC
I just did a fresh install of sierra, and have installed pyenv with homebrew and tested that it's working. I have a local 3.5.0 version of python in a virtualenv (read that 3.6 isn't working). I go through the tutorial and everything works until i try to compile...

running macos
 * Writing application template...
Template Python-macOS-template succesfully updated.
Project template: /Users/bigmac/.cookiecutters/Python-macOS-template
 * Determining best support package...
 * Installing support package...
Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Apple-support/3.5/macOS/Python-3.5-macOS-support.b4.tar.gz
 * Installing requirements...
No requirements.
 * Installing plaform requirements...
Collecting toga-cocoa
  Using cached toga_cocoa-0.2.15-py3-none-any.whl
Collecting rubicon-objc>=0.2.8 (from toga-cocoa)
  Using cached rubicon_objc-0.2.8-py3-none-any.whl
Collecting toga-core>=0.2.15 (from toga-cocoa)
  Using cached toga_core-0.2.15-py3-none-any.whl
Collecting colosseum>=0.1.6 (from toga-core>=0.2.15->toga-cocoa)
  Using cached colosseum-0.1.6-py3-none-any.whl
Installing collected packages: rubicon-objc, colosseum, toga-core, toga-cocoa
Successfully installed colosseum-0.1.6 rubicon-objc-0.2.8 toga-cocoa-0.2.15 toga-core-0.2.15
 * Installing project code...
Processing /Users/bigmac/Documents/python/python_3_projects/tutorial/helloworld
Installing collected packages: helloworld
  Running setup.py install for helloworld ... done
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Hello WOrld.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/bigmac/Documents/python/python_3_projects/tutorial/helloworld/macOS/Hello WOrld.app.

I tried the toga-demo and it worked fin on the same virtual env, if that helps. Also, after I get this running reliably, i'd like to contribute to the docs and the website. cheers!

**Comment by Ocupe** [comment] 2017-08-18 08:08
@itsjesseyo Could you share the code to reproduce the bug? 

I found this, maybe it is helpful: 

```
Error -10810
Basically, it means that the Launch Services framework is misbehaving and is encountering errors when trying to launch an application. When you encounter this error message, it is probably best to restart the machine.
```

**Comment by itsjesseyo** [comment] 2017-08-20 05:19
Howdy. So I tried rebooting on my laptop, and went do far as to re-wipe the desktop since it was fresh anyway. I also tried restarting if once it failed. As far as my code... If you are familiar with pyenv at all. I just...
pyenv install 3.5.0
pyenv local 3.5.0
mkvirtualenv brief
python --version
[python 3.5.0]
Then I copy n paste from this tutorial:
https://briefcase.readthedocs.io/en/latest/tutorials/tutorial-0.html

I've tried with the mac security allowing apps from anywhere, and with the default setting, and with the allow identified devs. thanks for the assist.

**Comment by itsjesseyo** [comment] 2017-09-04 01:33
i tried chmod +x and running the contents/macos/helloworld directly and I get this..

./macOS/helloworld.app/Contents/MacOS/helloworld: line 5: python/bin/python: No such file or directory

i've tried running from various directories within .app and out of it to make sure paths are correct. nothing works.

I also attempted this by following that pycon video that was just released. the python -m project_name works, but compiling the app and running solo just doesn't seem to work.

thanks for the help, yo.

**Comment by samredway** [comment] 2017-11-05 12:28
I can confirm this issue - exact same steps and same problem (I also used pyenv to create my local env with version 3.5.0). Error:

LSOpenURLsWithRole() failed with error -10810 for the file /Users/sam/dev/pybee/briefcase/tutorial/helloworld/macOS/Hello World.app.

**Comment by cculianu** [comment] 2018-01-24 14:20
Same here.  If you manually run the script it can't find python.  The python in Contents/Resources/python/bin is "python3" but it's looking for "python".

You can symlink it.  It will then run, but it spits out the following error:

Traceback (most recent call last):
  File "/Users/calin/Desktop/TestApp.app/Contents/Resources/python/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/calin/Desktop/TestApp.app/Contents/Resources/python/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/calin/Desktop/TestApp.app/Contents/Resources/app/TstApp/__main__.py", line 4, in <module>
    main().main_loop()
  File "/Users/calin/Desktop/TestApp.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/Users/calin/Desktop/TestApp.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 95, in _startup
    self._impl = NSApplication.sharedApplication()
TypeError: 'ObjCInstance' object is not callable

This is on High Sierra.

On El Capitan it fails with some shared library linking error.

It doesn't work for iOS targets either.

Any thoughts?

**Comment by freakboy3742** [comment] 2018-01-24 21:52
@cculianu Ok - that error explains it. The problem is an incompatibility with High Sierra in Toga. We've fixed the problem in the development branch, but 0.2.15 doesn't have the fix.

The problem is that briefcase can't (currently) be put into "install the development version" mode. We need to add support for either a "--pre" flag that enables installing prerelease versions from PyPI, and/or installing dependencies from GitHub.

**Comment by yelluw** [comment] 2018-02-26 16:48
Im currently experiencing the issue as well.

```
macOS 10.12.6
Python 3.6
```

When I run the executable directly from the the package contents I get this:
```
/Users/privera/Documents/code/py/my_app/my_app/macOS/my_app.app/Contents/MacOS/my_app ; exit;
/Users/privera/Documents/code/py/my_app/my_app/macOS/my_app.app/Contents/MacOS/my_app: line 5: python/bin/python: No such file or directory
```

When I run the commands: 

`python3 setup.py macos -s` I get this:

```
Starting my_app.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/privera/Documents/code/py/my_app/my_app/macOS/my_app.app.
```

**Comment by freakboy3742** [comment] 2018-02-27 03:11
@yelluw That's odd - if the error says `python/bin/python`, that means you're running a template that is trying to run Python 2, not Python 3. That means you're either using a stale macOS template, the wrong macOS template, or something *very* wrong is going on when setup.py runs...

Could I get you to provide:

 * The contents of `macOS/my_app.app/MacOS/myapp` 
 * The contents of `macOS/my_app.app/Contents/Resources/VERSIONS`
 * Confirmation that `macOS/my_app.app/Contents/Resources/python/bin/python3` exists
 * A full log of `python setup.py macos` running (after deleting the macOS directory from your project; I need to see a full rollout of the app)

**Comment by mrasband** [comment] 2018-02-28 23:05
I can reproduce the same issue so here is my output @freakboy3742 

I used `pyenv` to install `3.5.4` and used that in my virtualenv as the `-p` flag

```
$ which python
/Users/matthewrasband/.local/share/virtualenvs/native/bin/python
$ python --version
Python 3.5.4
$ cat macOS/Hello\ World.app/Contents/MacOS/Hello\ World
#!/bin/bash
CONTENTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
export PYTHONPATH="$CONTENTS_DIR/Resources/app":"$CONTENTS_DIR/Resources/app_packages"
cd "$CONTENTS_DIR/Resources"
python/bin/python -m helloworld
$ cat macOS/Hello\ World.app/Contents/Resources/VERSIONS
Python version: 3.5.5
Build: 8
---------------------
BZip2: 1.0.6
OpenSSL: 1.0.2n
XZ: 5.2.3
$ ls macOS/Hello\ World.app/Contents/Resources/python/bin
2to3              idle3.5           python3           python3.5-config  pyvenv
2to3-3.5          pydoc3            python3-config    python3.5m        pyvenv-3.5
idle3             pydoc3.5          python3.5         python3.5m-config
```

As I am sure you will notice, the `VERSIONS` is a bit odd (showing Python 3.5.5).

Here is the build log:

```
$ python setup.py macos -s
running macos

A directory named 'macOS' already exists. Would you like to replace it (y/N)? Y

 * Deleting existing content...
 * Writing application template...
Template Python-macOS-template succesfully updated.
Project template: /Users/matthewrasband/.cookiecutters/Python-macOS-template
 * Determining best support package...
 * Installing support package...
Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Apple-support/3.5/macOS/Python-3.5-macOS-support.b8.tar.gz
 * Installing requirements...
No requirements.
 * Installing plaform requirements...
Collecting toga-cocoa
  Using cached toga_cocoa-0.2.15-py3-none-any.whl
Collecting rubicon-objc>=0.2.8 (from toga-cocoa)
  Using cached rubicon_objc-0.2.10-py2.py3-none-any.whl
Collecting toga-core>=0.2.15 (from toga-cocoa)
  Using cached toga_core-0.2.15-py3-none-any.whl
Collecting colosseum>=0.1.6 (from toga-core>=0.2.15->toga-cocoa)
  Using cached colosseum-0.1.6-py3-none-any.whl
Installing collected packages: rubicon-objc, colosseum, toga-core, toga-cocoa
Successfully installed colosseum-0.1.6 rubicon-objc-0.2.10 toga-cocoa-0.2.15 toga-core-0.2.15
 * Installing project code...
Processing /Users/matthewrasband/Developer/scripts/native/helloworld
Installing collected packages: helloworld
  Running setup.py install for helloworld ... done
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Hello World.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/matthewrasband/Developer/scripts/native/helloworld/macOS/Hello World.app.

App started.
```

**Comment by freakboy3742** [comment] 2018-03-01 00:21
Right - If you're on High Sierra, then that makes sense. The app is being created with Toga 0.2.15, which doesn't support High Sierra.

If you modify your setup.py to explicitly require toga-cocoa==0.3.0.dev7, you'll get the High Sierra capable build of Toga, which should avoid the LSOpenURLsWithRole error.

**Comment by mrasband** [comment] 2018-03-01 00:28
🤦‍♂️ Sorry I thought I was being helpful sharing that output, thank you for the amazing work on this!

**Comment by yelluw** [comment] 2018-03-01 19:27
`macOS/my_app.app/MacOS/myapp`

<img width="428" alt="screen shot 2018-03-01 at 2 15 48 pm" src="https://user-images.githubusercontent.com/23017027/36864584-18277340-1d5b-11e8-8149-ae63650f1fad.png">

`Info.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>This</string>
	<key>CFBundleIconFile</key>
	<string>this.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.this.this</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>This</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
</dict>
</plist>
```

`MacOS/This` The executable:

```
#!/bin/bash
CONTENTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
export PYTHONPATH="$CONTENTS_DIR/Resources/app":"$CONTENTS_DIR/Resources/app_packages"
cd "$CONTENTS_DIR/Resources"
python/bin/python -m this
```

<img width="447" alt="screen shot 2018-03-01 at 2 22 58 pm" src="https://user-images.githubusercontent.com/23017027/36864911-127301f2-1d5c-11e8-8246-e02da10b25be.png">

`macOS/my_app.app/Contents/Resources/VERSIONS`

```
Python version: 3.6.3 
Build: 2
```

`Confirmation that macOS/my_app.app/Contents/Resources/python/bin/python3 exists`

<img width="1003" alt="screen shot 2018-03-01 at 2 25 09 pm" src="https://user-images.githubusercontent.com/23017027/36865120-998f0aaa-1d5c-11e8-895b-4a0a2687e231.png">


Working on this one:

```
A full log of python setup.py macos running (after deleting the macOS directory from your project; I need to see a full rollout of the app)```

**Comment by sanketdiwale** [comment] 2018-03-22 06:06
I am getting the same error LSOpenURLsWithRole() failed with error -10810 for the file as mrasband
I have OS X yosemite (10.10.5), Python 3.5.2 in  a virtualenv with toga.__version__ 0.3.0.dev8 and  briefcase.__version__ 0.2.1
In the setup.py for my trail application I have
``` 
# Desktop/laptop deployments
        'macos': {
            'app_requires': [
                'toga-cocoa==0.3.0.dev8',
            ]
        },
```
The application runs fine if I run it with python -m appname but if I try to deploy it to my mac with python setup.py macos -s I get the same error as mrasband and double clicking on the app icon does nothing (i.e. the app does not run). 

I also tried running the executable in the application package folder directly from the terminal and I got the following error:
```
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /macOS/Freedom.app/Contents/Resources/python/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: macOS/Freedom.app/Contents/Resources/python/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib

./Freedom: line 5: 15881 Trace/BPT trap: 5       python/bin/python3 -m freedom
```

**Comment by freakboy3742** [comment] 2018-03-23 03:04
@sanketdiwale That looks like it's a problem with the pre-built libraries on Yosemite. `_getentropy` was only added to macOS recently, so backwards compatibility is obviously an issue.

**Comment by sanketdiwale** [comment] 2018-03-23 09:16
Yes. Thanks, I upgraded to Sierra and the app worked fine now.

**Comment by freakboy3742** [comment] 2018-05-21 00:29
@daviewales I'm sure it's *possible*; the catch is working out what is required. It's somewhat difficult for me to test, because I don't have access to an older macOS box for testing purposes. 

If you've got access to an older macOS machine, you can help out by running the build process (cloning the repository and running `make` should be all you need to do), and reporting the specific build problem you have - or better still, providing any patches needed to correct the build process.

**Comment by cculianu** [comment] 2018-05-21 08:07
Ah -- good to know that is the problem!  Aye given Apple's insistence on
not allowing you to downgrade -- it's hard to get your hands on an older
MacOS.

Since I actually write MacOS apps, I actually like to keep my old macOS's
around on VM's.

When I get a chance maybe I can take a look at it as well.

**Comment by daviewales** [comment] 2018-05-22 02:41
For those trying to clone and `make`, keep in mind you really want to clone and `make` these:

- [Python MacOS Template](https://github.com/pybee/Python-macOS-template)
- [Python Apple Support](https://github.com/pybee/Python-Apple-support)
    - Note that you need to switch to the relevant branch for your Python version

**Comment by daviewales** [comment] 2018-05-22 04:07
The clearest statement of the problem I have found so far is in a [gnutls issue](https://gitlab.com/gnutls/gnutls/issues/142).

(Our issue is not with gnutls, but rather with the weakly defined symbols in the macOS SDK)

This suggests we may be able to fix it by simply adding

    LDFLAGS="$LDFLAGS -Wl, -no_weak_imports"

This should only be set on macOS 10.11, with Xcode 8 and CLI tools 8.

**Comment by daviewales** [comment] 2018-05-22 05:11
OK. I have a working build!

Steps:

1. Clone [Python Apple support](https://github.com/pybee/Python-Apple-support/tree/3.6)
2. Checkout remote branch for Python 3.6 `git checkout -b 3.6 origin/3.6`
3. `make macOS`
4. Run `./build/macOS/python/bin/python3`
5. No symbol errors!

In contrast, downloading the [pre-built version](https://s3-us-west-2.amazonaws.com/pybee-briefcase-support/Python-Apple-support/3.6/macOS/Python-3.6-macOS-support.b6.tar.gz), extracting and running `./python/bin/python3` causes the familiar `_getentropy` dyld issue.

**Comment by daviewales** [comment] 2018-05-22 05:36
I'm not quite sure about the best way to patch this.

It appears that simply building on macOS 10.11.6 with the Xcode Command Line tools version 8.2.1 fixes the issue.
Perhaps a separate package could be uploaded specifically for users running 10.11?

Alternatively, perhaps someone with access to 10.12 or higher could try building

**Comment by sbeaumont** [comment] 2018-06-03 13:50
I get this error too. Based on my research, I found that it's a somewhat generic error message, and you can get more information by doing "Show Package Contents" and double clicking the executable in the macOS folder directly, In my case I see this [I removed my personal details from the results below]:

/Users/.../ontw/beeware-helloworld/helloworld/macOS/Hello\ World.app/Contents/MacOS/Hello\ World ; exit;
$ /Users/.../ontw/beeware-helloworld/helloworld/macOS/Hello\ World.app/Contents/MacOS/Hello\ World ; exit;
/Users/.../ontw/beeware-helloworld/helloworld/macOS/Hello World.app/Contents/MacOS/Hello World: line 5: python/bin/python3: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...38 completed.

[Process completed]

So in my case it tries to find python3, but can't.

**Comment by sbeaumont** [comment] 2018-06-03 23:09
@daviewales Yep, that works. Is there an automated way to get this done, or did I not use a script correctly?

**Comment by freakboy3742** [comment] 2018-06-03 23:42
@daviewales I'm a little surprised a download failure could trigger this - I would have thought an incomplete (or failed) download would have raised an error during the installation process. However, errors like this one keep being reported, so I can't rule anything out. Any details you (or @sbeaumont) can provide about the manner in which the download failed (and any log messages that correspond to that failure) would be very helpful.

**Comment by daviewales** [comment] 2018-06-03 23:48
I'll go through the installation from scratch later today.

When I first installed this several weeks ago, the `python` directory was completely missing from the `Resources` folder. However, when I ran the install a second time, it worked. The only difference I could think of was a bad download.

**Comment by sbeaumont** [comment] 2018-06-04 08:27
Yep, that's it! I was at a location with a bad internet connection yesterday. It would hang for a while while running setup.py, I would have to interrupt it and run it again. It would then run to completion (or so I thought). By throwing away the macOS folder and re-running setup.py at home it completed in one go, and the python directory was there, and everything runs smoothly.

A fix could be to throw away the target folder completely when rerunning setup.py, but a robust solution would also have the app self-report on a broken build, like a missing python folder.

**Comment by freakboy3742** [comment] 2018-06-04 11:27
@daviewales Yes - and that's what the code *should* already be doing. It downloads support packages into `~/.briefcase`; and should raise error messages if the download doesn't succeed. However, testing broken network behavior is a tricky beast, so I won't guarantee the error handling is 100% robust. I'm a *little* surprised "fail silently" is the resulting behavior, though...

**Comment by jacebrowning** [comment] 2019-05-07 18:58
I just ran into a similar problem on the PyCon wifi. Upon running `$ python setup.py macos -s` the "Installing support package..." step seemed to time out so I cancelled it. A second invocation of `$ python setup.py macos -s` seemly attempted to use a partially downloaded `Python-3.7-macOS-support.b1.tar.gz` resulting in **error -10810**.

To get back into a working state, I had to:

```
$ rm -rf ~/.briefcase
$ python setup.py macos -s
```
---

A couple proposals:

- Download support packages with a temporary file extension (e.g. `.tmp`) that is later removed once of the download has completed.

- Add a checksum to the filename to verify a complete download. Delete incomplete files and download them again.

**Comment by freakboy3742** [comment] 2019-05-07 20:11
@jacebrowning Those are both good suggestions; error handling is something that briefcase doesn't currently handle well (and, ironically, is something that is especially important in PyCon sprint-situations because the internet is so flaky)

Another option to put on the table would be to improve the error reporting of the macOS stub. As it currently stands, the bootstrap script for a macOS app does a very naïve "start the Python interpreter and assume it works" startup sequence. If Python is missing, or is corrupted, or the Python code raises an error, those errors are almost entirely opaque. 

It shouldn't be *that* hard to add simple error code checking to the bootstrap script, and/or catch errors and display errors any problems to the user...

**Comment by psytron** [comment] 2019-09-23 08:00
I am getting same error: 
 
$> python setup.py macos -s

 * Confirming prerequisites...

 * Looking for Xcode...
Xcode 10.3
Build version 10G8

 * Looking for Command Line Tools...
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-cocoa==0.3.0.dev14
  Using cached https://files.pythonhosted.org/packages/32/f0/c99e6d786663317b6fc8b880132e5eb87d85a7d71b545c9853968f10357a/toga_cocoa-0.3.0.dev14-py3-none-any.whl
Collecting rubicon-objc>=0.3.0 (from toga-cocoa==0.3.0.dev14)
  Using cached https://files.pythonhosted.org/packages/c7/1d/ef53fc55e035f4502a120d722d05b612830ffb0a5e923440f83bea091c7b/rubicon_objc-0.3.1-py2.py3-none-any.whl
Collecting toga-core==0.3.0.dev14 (from toga-cocoa==0.3.0.dev14)
  Using cached https://files.pythonhosted.org/packages/95/3f/2e6188f4d0174435811e103b24c79cdeaa8679985fe2e430fd6eb992f29d/toga_core-0.3.0.dev14-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev14->toga-cocoa==0.3.0.dev14)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: rubicon-objc, travertino, toga-core, toga-cocoa
Successfully installed rubicon-objc-0.3.1 toga-cocoa-0.3.0.dev14 toga-core-0.3.0.dev14 travertino-0.1.2
 * Installing project code...
Processing /Users/psy/1m/apps/generic/apdexapp
Building wheels for collected packages: apdexapp
  Building wheel for apdexapp (setup.py) ... done
  Created wheel for apdexapp: filename=apdexapp-0.0.1-cp36-none-any.whl size=2527 sha256=a2d47796ae944d99aead2bbe6e9c354af5f65c8b3f1d458583fbf51e0d5355d3
  Stored in directory: /private/var/folders/qk/qrys9w8n5jq3q257ctlnjn540000gn/T/pip-ephem-wheel-cache-y2z9iit0/wheels/cf/e9/f7/2e82db4f8c72893b773fda342812b07c2f117837ccc7becd3b
Successfully built apdexapp
Installing collected packages: apdexapp
Successfully installed apdexapp-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Building DMG file...
Starting apdexapp.app

LSOpenURLsWithRole() failed with error -10810 for the file /Users/psy/1m/apps/generic/apdexapp/macOS/apdexapp.app.

**Comment by freakboy3742** [comment] 2019-09-23 17:16
@psytron Thanks for the report. By way of debugging, if you can provide the details described in [This comment](https://github.com/beeware/briefcase/issues/66#issuecomment-368732575), that will help us narrow down what has happened.

The other way to debug this is to run the application manually. The LSOpenUrlsWithRole() error effectively means "the application crashed when starting", which can be due to a packaging error, but it can also be due to an error in the application itself. Unfortunately, opening the application using Finder hides the logs, but you can reproduce what happens when you click on the app icon by running the application script from the command line:

`macOS/apdexapp.app/Contents/MacOS/apdexapp`

Those logs will hopefully give some more insight into the source of the problem.

**Comment by psytron** [comment] 2019-09-29 07:02
@freakboy3742 thanks, I followed your process and indeed it is now showing more specific import errors

**Comment by freakboy3742** [comment] 2019-12-21 00:47
The underlying problem here is a need for better error handling in the macOS template; closing this issue in preference for beeware/briefcase-macOS-app-template#1

**Closed by freakboy3742** 2019-12-21 00:47 UTC

**Comment by kw3ku** [comment] 2020-02-28 11:29
In my case for this error =>> LSOpenURLsWithRole() failed for the application /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app with error -10810.

I solved it by running the Xcode after i downloaded from apple developer. I had the 10.2.1 XCODE and after deleting and downloading the new one, i didn't run it first before expecting the emulator to work. So, run it first which will install some few things for the new install.

**Comment by freakboy3742** [comment] 2020-02-29 01:56
@kw3ku It sounds to me like you've hit a different error with a very similar error message.

Your error message is about the *iOS simulator*, not a macOS app. I can't say I've seen the iOS simulator raise this error - but the situation you describe (a clean Xcode install) is also one that is difficult to replicate. 

Breifcase 0.3 *should* be checking to confirm that all the required tools are available and installed; if you've been able to generate this error using v0.3, then we clearly need to improve those checks.

**Comment by TinBane** [comment] 2020-03-04 01:47
I'm getting the same issue on high sierra.

`adrian$ briefcase create

[app] Generating application template...
Using app template: https://github.com/beeware/briefcase-macOS-app-template.git
Using existing template (sha 8775207d438ce51290a487d92cc975b4a21485d2, updated Tue Jan  7 16:20:02 2020)

[app] Installing support package...
Using support package https://briefcase-support.org/python?platform=macOS&version=3.8
Python-3.8-macOS-support.b1.tar.gz already downloaded
Unpacking support package...

[app] Installing dependencies...
Collecting toga-cocoa>=0.3.0.dev18
  Using cached toga_cocoa-0.3.0.dev18-py3-none-any.whl (51 kB)
Collecting toga-core==0.3.0.dev18
  Using cached toga_core-0.3.0.dev18-py3-none-any.whl (512 kB)
Collecting rubicon-objc>=0.3.0
  Using cached rubicon_objc-0.3.1-py2.py3-none-any.whl (66 kB)
Collecting travertino>=0.1.0
  Using cached travertino-0.1.2-py3-none-any.whl (15 kB)
Installing collected packages: travertino, toga-core, rubicon-objc, toga-cocoa
Successfully installed rubicon-objc-0.3.1 toga-cocoa-0.3.0.dev18 toga-core-0.3.0.dev18 travertino-0.1.2

[app] Installing application code...
Installing src/app...

[app] Installing application resources...
Installing src/app/resources/icon.icns as application icon...

[app] Created macOS/App`

But when I try this:

 ```
ABIS:app adrian$ briefcase run

[app] Starting app...

LSOpenURLsWithRole() failed with error -10810 for the file /Users/adrian/python/app/macOS/App/App.app.

Unable to start app app.
```

But I'm running 0.3.0.dev18 and using it on mac OS X.

**Comment by Victor2333** [comment] 2020-04-22 00:36
> @itsjesseyo Could you share the code to reproduce the bug?
> 
> I found this, maybe it is helpful:
> 
> ```
> Error -10810
> Basically, it means that the Launch Services framework is misbehaving and is encountering errors when trying to launch an application. When you encounter this error message, it is probably best to restart the machine.
> ```

Restart machine is working.
