### ISSUE TITLE
Briefcase build command builds stale AppImage

### ISSUE THREAD

**Issue by jhakonen** [beeware/briefcase#660] opened 2022-01-26 17:23 UTC
**Describe the bug**
Once an AppImage has been built from a Python project, any subsequent calls to `briefcase build` just builds the same AppImage again, ignoring any changes to project's sources.

**To Reproduce**
1. Create new Toga project using default answers:
```bash
briefcase new
cd helloworld
```
2. Then build AppImage and execute it:
```bash
briefcase build
linux/Hello_World-0.0.1-x86_64.AppImage
```
You will see this:

![HelloWorld](https://user-images.githubusercontent.com/1950698/151213526-4d0c7f78-e227-4d94-bab5-673d36c5a82f.png)

3. Next in `src/helloworld/app.py` change window title from:
```python
self.main_window = toga.MainWindow(title=self.formal_name)
```
To:
```python
self.main_window = toga.MainWindow(title='Hello There')
```
4. Build AppImage again and execute it: 
```bash
briefcase build
linux/Hello_World-0.0.1-x86_64.AppImage
```
However the title remains as "Hello World":

![HelloWorld](https://user-images.githubusercontent.com/1950698/151213526-4d0c7f78-e227-4d94-bab5-673d36c5a82f.png)

**Expected behavior**
I would expect the window title to be "Hello There", like this:

![HelloThere](https://user-images.githubusercontent.com/1950698/151213639-eb8fcd8d-5df1-48fc-9414-0c8e45a51b19.png)

**Workaround**
Delete `linux` folder before building the AppImage, then the title becomes "Hello There" as expected. However this will cause the build command to download Python dependencies again, which can take time. Not ideal.

**Environment:**
 - Operating System: Pop!_OS 20.04
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30

**Comment by freakboy3742** [comment] 2022-01-28 06:26
Thanks for the report! This might be a little complex to fix, as the fix will require re-generating a template over an existing rolled-out template - but it's definitely a bug that should be fixed.

**Comment by freakboy3742** [comment] 2022-03-28 01:00
Doing some housekeeping, this is a duplicate of #472.

**Closed by freakboy3742** 2022-03-28 01:00 UTC
Labels: bug, up-for-grabs
