### ISSUE TITLE
Error when running Toga Application

### ISSUE THREAD

**Issue by Torilla** [beeware/briefcase#679] opened 2022-03-05 17:24 UTC
**Describe the bug**
When following the tutorial everything works fine
until then application is run via `briefcase run`. It crashes
when trying to import some ligobject. The same happens when
the AppImage is executed directly.

**To Reproduce**
Follow the tutorial provided on https://docs.beeware.org/en/latest/tutorial/tutorial-3.html

**Expected behavior**
The app should start.

**Screenshots**
![Screenshot from 2022-03-05 18-18-31](https://user-images.githubusercontent.com/30720484/156893645-eb17191b-b9dc-4ae5-b21f-3fc0d3040b09.png)

**Environment:**
 - Operating System: Debian GNU/Linux 11 (bullseye)
 - Python version: 3.9.2
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: 0.3.0

**Comment by freakboy3742** [comment] 2022-03-06 02:53
This looks like it could be a duplicate of #631 - see [this comment](https://github.com/beeware/briefcase/issues/631#issuecomment-1042361287) (and the follow ups) for a possible manual fix.

**Comment by Torilla** [comment] 2022-03-06 11:24
I tried all 3 approaches as far as I undestood them, however the error remains or in case of injecting the old libraries I get
```
   [...]
    import gi
  File "/tmp/.mount_patchenjk806/usr/app_packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libpcre.so.1: cannot open shared object file: No such file or directory

```

**Comment by freakboy3742** [comment] 2022-06-27 06:43
Closing as a likely duplicate of #718.

**Closed by freakboy3742** 2022-06-27 06:43 UTC
Labels: bug, linux, more-details
