### ISSUE TITLE
Importing win32api (pywin32) in Briefcase Run 

### ISSUE THREAD

**Issue by MosGeo** [beeware/briefcase#835] opened 2022-08-20 15:24 UTC
**Describe the bug**
Importing win32api works during `dev` but not `run`. Note that `pywin32` is added as a requirement and it is installed in site_packages. 

**To Reproduce**
1. Create new briefcase project
2. Add `pywin32` as a requirement in `pyproject.toml`
3. Add `import win32api` to `app.py`
4. Run `briefcase run -u`

**Expected behavior**
Application runs

**Environment:**
 - Operating System: Windows 10 64 Bit
 - Python version: 3.10
 - Software versions:
   - Briefcase: 0.3.9

**Additional context**
I tried the workaround as suggested in a very old closed issue by adding the paths manually but it didn't help (#102).

**Comment by rmartin16** [comment] 2022-08-20 16:20
Can you try `briefcase dev -d`? That'll update (and installed any new) Python dependencies for the `dev` command.

**Comment by MosGeo** [comment] 2022-08-20 16:39
Both the run and dev environments are using the latest versions of all dependencies.

Ps. It works in dev but not in run. The initial post was confusing.

**Comment by rmartin16** [comment] 2022-08-20 17:28
Ahh....ok. I can replicate this as well now. Given the existence of this [post install script](https://github.com/mhammond/pywin32/blob/main/pywin32_postinstall.py) for `pywin32`, it looks like this package will require some extra tweaking; the use-case here appears to fall outside of what they're [expecting](https://github.com/mhammond/pywin32#installing-via-pip). Although, I'll have to defer to others on exactly might need to be done.

**Comment by freakboy3742** [comment] 2022-08-22 05:11
I have a sneaking suspicion that this might be a duplicate of #381 - at least in spirit. There are clearly a class of Python modules that are *very* sensitive to the assumption that they're being installed using the interpreter that will eventually run them.

**Comment by MosGeo** [comment] 2022-08-22 07:05
@freakboy3742 just took a quick look. Yes, I suspect it is the same issue.

**Comment by freakboy3742** [comment] 2022-09-30 04:24
Closing as a duplicate of #381.

**Closed by freakboy3742** 2022-09-30 04:24 UTC
Labels: bug, up-for-grabs, windows
