### ISSUE TITLE
Module `pandas` (with binary dependencies) not installed correctly for macOS & ARM

### ISSUE THREAD

**Issue by clstaudt** [beeware/briefcase#657] opened 2022-01-11 16:17 UTC
**Describe the bug**

My application depends on `pandas`, which in turn depends on `numpy`. Trying to build a macOS app fails with the following error:

```
2022-01-11 11:34:34.290 MyApp[4341:69616] 	/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app_packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
```

This is a known issue when working on an ARM Mac and trying to install libraries with C/C++/Fortran components via pip. My usual solution is to install these packages from `conda-forge` via [miniforge](https://github.com/conda-forge/miniforge). It seems that this solution is not (yet) available for Beeware apps, correct?

Full output on app start:

```
╰─ ./macOS/app/MyApp/MyApp.app/Contents/MacOS/MyApp                                                                   (MyApp) 
2022-01-11 11:34:34.288 MyApp[4341:69616] Traceback (most recent call last):
2022-01-11 11:34:34.288 MyApp[4341:69616]   File "/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/Support/Python/Resources/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2022-01-11 11:34:34.289 MyApp[4341:69616]     return _run_code(code, main_globals, None,
2022-01-11 11:34:34.289 MyApp[4341:69616]   File "/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/Support/Python/Resources/lib/python3.9/runpy.py", line 87, in _run_code
2022-01-11 11:34:34.289 MyApp[4341:69616]     exec(code, run_globals)
2022-01-11 11:34:34.289 MyApp[4341:69616]   File "/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app/MyApp_app/__main__.py", line 1, in <module>
2022-01-11 11:34:34.289 MyApp[4341:69616]     from MyApp_app.app import main
2022-01-11 11:34:34.289 MyApp[4341:69616]   File "/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app/MyApp_app/app.py", line 8, in <module>
2022-01-11 11:34:34.289 MyApp[4341:69616]     import pandas
2022-01-11 11:34:34.289 MyApp[4341:69616]   File "/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app_packages/pandas/__init__.py", line 16, in <module>
2022-01-11 11:34:34.289 MyApp[4341:69616]     raise ImportError(
2022-01-11 11:34:34.289 MyApp[4341:69616] ImportError: Unable to import required dependencies:
2022-01-11 11:34:34.289 MyApp[4341:69616] numpy: 
2022-01-11 11:34:34.289 MyApp[4341:69616] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
2022-01-11 11:34:34.289 MyApp[4341:69616] Importing the numpy C-extensions failed. This error can happen for
2022-01-11 11:34:34.289 MyApp[4341:69616] many reasons, often due to issues with your setup or how NumPy was
2022-01-11 11:34:34.289 MyApp[4341:69616] installed.
2022-01-11 11:34:34.289 MyApp[4341:69616] We have compiled some common reasons and troubleshooting tips at:
2022-01-11 11:34:34.289 MyApp[4341:69616]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
2022-01-11 11:34:34.289 MyApp[4341:69616] Please note and check the following:
2022-01-11 11:34:34.289 MyApp[4341:69616]   * The Python version is: Python3.9 from "/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/./macOS/app/MyApp/MyApp.app/Contents/MacOS/MyApp"
2022-01-11 11:34:34.289 MyApp[4341:69616]   * The NumPy version is: "1.22.0"
2022-01-11 11:34:34.289 MyApp[4341:69616] and make sure that they are the versions you expect.
2022-01-11 11:34:34.289 MyApp[4341:69616] Please carefully study the documentation linked above for further help.
2022-01-11 11:34:34.290 MyApp[4341:69616] Original error was: dlopen(/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app_packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): no suitable image found.  Did find:
2022-01-11 11:34:34.290 MyApp[4341:69616] 	/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app_packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
2022-01-11 11:34:34.290 MyApp[4341:69616] 	/Users/cls/Documents/Work/Projects/PF/Dev/MyApp-app/macOS/app/MyApp/MyApp.app/Contents/Resources/app_packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
fish: Job 1, './macOS/app/MyApp/MyApp.app...' terminated by signal SIGTERM (Polite quit request)
```

Full output of the build step (seemingly successsful):

```
╰─ briefcase create                                                                                                

Application MyApp_app already exists; overwrite [y/N]? y

[MyApp_app] Removing old application bundle...

[MyApp_app] Generating application template...
Using app template: https://github.com/beeware/briefcase-macOS-app-template.git, branch 3.9
Using existing template (sha 115cb2cd078d2d6383e45bc590b1b755d7d41a4f, updated Mon Oct 25 20:56:14 2021)

[MyApp_app] Installing support package...
Using support package https://briefcase-support.org/python?platform=macOS&version=3.9
... using most recent revision
Python-3.9-macOS-support.b5.tar.gz already downloaded
Unpacking support package...

[MyApp_app] Installing dependencies...
Collecting pandas
  Using cached pandas-1.3.5-cp39-cp39-macosx_11_0_arm64.whl
Collecting sqlmodel
  Using cached sqlmodel-0.0.6-py3-none-any.whl (21 kB)
Collecting pyicloud
  Using cached pyicloud-0.10.2-py3-none-any.whl
Collecting toga-cocoa>=0.3.0.dev20
  Using cached toga_cocoa-0.3.0.dev30-py3-none-any.whl (61 kB)
Collecting numpy>=1.20.0
  Using cached numpy-1.22.0-cp39-cp39-macosx_11_0_arm64.whl (12.8 MB)
Collecting pytz>=2017.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting SQLAlchemy<1.5.0,>=1.4.17
  Using cached SQLAlchemy-1.4.29-cp39-cp39-macosx_11_0_arm64.whl
Collecting pydantic<2.0.0,>=1.8.2
  Using cached pydantic-1.9.0-cp39-cp39-macosx_11_0_arm64.whl (2.4 MB)
Collecting sqlalchemy2-stubs
  Using cached sqlalchemy2_stubs-0.0.2a19-py3-none-any.whl (190 kB)
Collecting keyrings.alt<=3.2.0,>=1.0
  Using cached keyrings.alt-3.2.0-py2.py3-none-any.whl (20 kB)
Collecting tzlocal==2.0.0
  Using cached tzlocal-2.0.0-py2.py3-none-any.whl (15 kB)
Collecting certifi>=2019.11.28
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting click<=7.1.1,>=6.0
  Using cached click-7.1.1-py2.py3-none-any.whl (82 kB)
Collecting keyring<=9.3.1,>=8.0
  Using cached keyring-9.3.1-py2.py3-none-any.whl (35 kB)
Collecting six>=1.14.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting future>=0.18.2
  Using cached future-0.18.2-py3-none-any.whl
Collecting requests>=2.20.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting rubicon-objc>=0.3.0
  Using cached rubicon_objc-0.4.2-py3-none-any.whl (58 kB)
Collecting toga-core==0.3.0.dev30
  Using cached toga_core-0.3.0.dev30-py3-none-any.whl (489 kB)
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
Installing collected packages: urllib3, typing-extensions, travertino, six, pytz, idna, charset-normalizer, certifi, tzlocal, toga-core, sqlalchemy2-stubs, SQLAlchemy, rubicon-objc, requests, python-dateutil, pydantic, numpy, keyrings.alt, keyring, future, click, toga-cocoa, sqlmodel, pyicloud, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
black 21.10b0 requires click>=7.1.2, but you have click 7.1.1 which is incompatible.
Successfully installed SQLAlchemy-1.4.29 certifi-2021.10.8 charset-normalizer-2.0.10 click-7.1.1 future-0.18.2 idna-3.3 keyring-9.3.1 keyrings.alt-3.2.0 numpy-1.22.0 pandas-1.3.5 pydantic-1.9.0 pyicloud-0.10.2 python-dateutil-2.8.2 pytz-2021.3 requests-2.27.1 rubicon-objc-0.4.2 six-1.16.0 sqlalchemy2-stubs-0.0.2a19 sqlmodel-0.0.6 toga-cocoa-0.3.0.dev30 toga-core-0.3.0.dev30 travertino-0.1.3 typing-extensions-4.0.1 tzlocal-2.0.0 urllib3-1.26.8

[MyApp_app] Installing application code...
Installing src/MyApp_app...

[MyApp_app] Installing application resources...
Installing src/MyApp_app/resources/MyApp_app.icns as application icon...

[MyApp_app] Created macOS/app/MyApp
```

**To Reproduce**
1. Start a new project with `briefcase new` 
2. add pandas to requirements and import pandas in the code
3. on a Mac with ARM processor, build and try to launch the app

**Expected behavior**

Beeware should install and package the matching binary components for popular Python libraries like `pandas`.

**Environment:**
 - Operating System: macOS 11.6.2
 - Python version: 3.9.7
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30
   - ...

**Additional context**

**Comment by freakboy3742** [comment] 2022-01-13 01:43
Thanks for the report. As you've noted, this is primarily caused by the complication around macOS adoption of ARM, and the interaction of that change with binary modules on pip. 

At present, Briefcase is bound to using `pip`; so this is effectively a "known problem caused by upstream limitations". I'll keep this ticket open because we inherit this problem transitively, but there's a limit to how much *Briefcase* can do to address this directly.

There has been discussion around whether a `conda`-based Briefcase package is possible. There are some technical limitations around `conda` that are the limitation in that case; see #596 for the discussion.

**Comment by freakboy3742** [comment] 2022-07-14 04:07
I'm going to close this on the basis that there's essentially nothing we can do. Any fix is entirely dependent on upstream packagers building their modules to support multiple architectures; and the pip ecosystem doesn't (AFAIK) have any tooling to pre-emptively identify if this has been done.

**Closed by freakboy3742** 2022-07-14 04:07 UTC
Labels: bug, macOS
