### ISSUE TITLE
Works in dev mode but not in run mode

### ISSUE THREAD

**Issue by RiccardoBarbieri** [beeware/briefcase#478] opened 2020-08-23 18:00 UTC
**Describe the bug**
When I run 'briefcase dev' in vs code terminal with beeware venv active the app works just fine but when i run 'briefcase create', 'briefcase build' and 'briefcase run' on windows the terminal says Unable to start app animals

To reproduce I link here a github repo with the entire folder created by 'briefcase create', it is in animals sub-folder:
https://github.com/RiccardoBarbieri/beeware-projects

**Environment:**
 - Operating System: Windows
 - Python version: 3.8.1

**Comment by saroad2** [comment] 2020-08-23 18:25
Hey!

When you run `briefcase dev` you run the app in your own virtual environment, but when you run `briefcase run` you run it in with an isolated *python* runner with only specific libraries.

In order to make it work, you should add the dependencies in your *pyproject.toml* file. that would probably solve the problem.

**Comment by RiccardoBarbieri** [comment] 2020-08-23 18:43
> Hey!
> 
> When you run `briefcase dev` you run the app in your own virtual environment, but when you run `briefcase run` you run it in with an isolated _python_ runner with only specific libraries.
> 
> In order to make it work, you should add the dependencies in your _pyproject.toml_ file. that would probably solve the problem.

Hey @saroad2, thanks for you reply. 

So you're saying that I just have to add the dependencies (by dependencies you mean external libraries that I use in my code? In this specific case I use lxml and requests) but I have no clue on how to do it. I looked at the file and I don't really understand what's going on inside that .toml, could you set me in the right path?

**Comment by saroad2** [comment] 2020-08-23 18:47
Sure. Here's your *pyproject.toml* file:

``` toml
[tool.briefcase.app.animals]
formal_name = "AnimalS"
description = "Search animals by specifing the first and last letter"
icon = "src/animals/resources/animals"
sources = ['src/animals']
requires = []  # <- Add dependencies here
```

If you want an example, you can take a look at my project [here](https://github.com/EddLabs/eddington-gui/blob/master/pyproject.toml).

I'm closing the issue for now. If this problem still occurring, please feel free to reopen the issue.

**Closed by saroad2** 2020-08-23 18:47 UTC
Labels: bug

**Comment by ioanfesteu** [comment] 2020-11-17 09:02
Hi!
I am ecountering the same problem. When running `briefcase dev` everything runs smooth but when running `briefcase run` it throws `Unable to start app headless` . I have updated `pyproject.toml` with the required dependencies but the error still persists. App is nothing fancy, I am trying to run a headless app, without any GUI, the only dependencies are `bottle` and `requests`. 
My environment is Windows 10 with Python 3.8.6.
When I created the new project I selected `None` for the GUI Toolkit.

**Comment by freakboy3742** [comment] 2020-11-17 09:07
@ioanfesteu After you made the change to `pyproject.toml`, did you run `briefcase update -d` to update the dependencies of the packaged app?

**Comment by ioanfesteu** [comment] 2020-11-17 09:16
Yes I did `briefcase update -d`.

**Comment by ErionTp** [comment] 2020-11-20 00:32
I'm having exactly the same problem as @ioanfesteu

**Comment by ronald-jaepel** [comment] 2020-12-28 16:34
I'm also encountered this error trying to build a bare-bones application on Windows. 
I was able to fix it by testing which dependency causes the error ('numpy>=1.19.2'), checking for the version that briefcase installed (1.19.4) and then changing the dependency to 'numpy==1.19.2'. Maybe this can help @ioanfesteu and @ErionTp.

**Comment by Imke7** [comment] 2021-01-02 15:02
I'm facing the same problem. Everything works fine with the `briefcase dev` command, but `briefcase run` doesn't work. I have all the dependencies I need specified in the `pyproject.toml` file, but I'm not sure if I have the right versions. I'm pretty new to Python and beeware and I don't know how to test this. @ronald-jaepel, could you explain how you did that? Or could there be another problem?

**Comment by ronald-jaepel** [comment] 2021-01-02 20:22
@Imke7 

First approach: 
1. get a list of installed packages in your environment (if you use pip: `pip list`, if you use conda: `conda list`).
2. compare the package versions to the ones that briefcase reports as installing during `briefcase create`
3. for discrepancies set the exact package version as the one in your environment in your pyproject.toml as mentioned in my first comment
Second approach:
1. use an absolute bare-bones example from beeware with briefcase and test if that works with `briefcase dev` and `briefcase run`
3. if `briefcase run` doesn't work: it's another problem and you should start another bug report as this one seems to focus on dependency-caused problems
4. if `briefcase run` works, gradually add imports and dependencies one at a time until you find the package that breaks `briefcase run` and create a new bug report with the relevant info.

If you have any other questions or need more detailed help let me know.

**Comment by Imke7** [comment] 2021-01-05 08:27
@ ronald-jaepel, Thanks for your explanation! I found two packages that didn't match the packages listed with pip list. So I changed them, but I still got the same error. I tried the second approach and turns out, its pyowm that causes the error. However, I specified the right version, so I'm still stuck...

**Comment by ronald-jaepel** [comment] 2021-01-05 15:24
In that case I'm out of ideas. I think you could start a new issue report with all the system info and a minimal working example (well, minimal not-working example in this case) that can reproduce the bug. Perhaps the devs can help you. Good luck!

**Comment by aerickson** [comment] 2021-02-24 11:35
I've experienced Android code not getting updated when making changes to the src project.

`briefcase update -d; briefcase build android; briefcase run android -d @beePhone` doesn't always pickup the changes. If I do `rm -rf android; briefcase create android` before the previous command it always picks up the changes.

**Debugging tips**: `adb logcat` will show the current error the Android app is having.

You can get the same debugging output on MacOS:

if `briefcase build macOS` produces: `macOS/Test/Test.app`
then to debug run: `./macOS/Test/Test.app/Contents/MacOS/Test`

**Comment by itinerishu** [comment] 2021-06-14 12:43
I had the same problem. In my case tkinter module caused the error, I don'know why. I used it only to determine the screen size. Removing the import fixed the problem.

**Comment by freakboy3742** [comment] 2021-06-14 12:48
@itinerishu If you're using tkinter, it won't ever under Briefcase without using a custom Python support package. Briefcase doesn't ship with Tkinter support by default.

**Comment by itinerishu** [comment] 2021-06-14 12:58
> @itinerishu If you're using tkinter, it won't ever under Briefcase without using a custom Python support package. Briefcase doesn't ship with Tkinter support by default.

Now I know, thanks :)

**Comment by lev007-ops** [comment] 2021-12-20 07:49
Hello, I have such a project structure:
![image](https://user-images.githubusercontent.com/64062569/146731011-3bed37b6-a0d1-42d6-a1e9-281f12e9111f.png)

but when I write cd qr_generator in the telminal (vs code), and then briefcase dev, I get an error:

```
(.venv) C:\Users\Дом\Desktop\Py\PY\qr_generator\qr_generator>briefcase dev

[qr_generator] Starting in dev mode...
Traceback (most recent call last):
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\qr_generator\src\qr_generator\__main__.py", line 4, in <module>
    main().main_loop()
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\qr_generator\src\qr_generator\app.py", line 41, in main
    return qrgenerator()
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga\app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga\platform.py", line 53, in get_platform_factory
    from toga_winforms import factory
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga_winforms\factory.py", line 1, in <module>
    from .app import App, MainWindow
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga_winforms\app.py", line 9, in <module>
    from .keys import toga_to_winforms_key
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga_winforms\keys.py", line 6, in <module>
    from .libs import WinForms
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga_winforms\libs\__init__.py", line 1, in <module>
    from .fonts import (  # noqa: F401
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga_winforms\libs\fonts.py", line 13, in <module>
    from .winforms import (
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\toga_winforms\libs\winforms.py", line 3, in <module>
    import clr
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "C:\Users\Дом\Desktop\Py\PY\qr_generator\.venv\lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

Unable to start application 'qr_generator'
```


The python version is 3.8.0. (it still costs 3.9, but venv is built on 3.8.0


Command line prefix - (.venv)

Python -V command: Python 3.8.0

What to do on windows 10?

**Comment by monzelr** [comment] 2022-02-11 20:12
Hi,

I am wondering if there is an easier way to see if the python depencies are correct.

Actually my (with Briefcase shipped) application runs in dev mode, but not in run mode.

However, to see the difference between 'dev' and 'run' I first need 
- to package the app
- install it on windows
- modify the shortcut (*.lnk file) (pythonw.exe to python.exe)
and then
- open the .lnk file in window's cmd.exe

After these steps I just think: "damn, jsonschema is missing... ok, next iteration"
image for example:
![image](https://user-images.githubusercontent.com/60315601/153662609-c9e9e6cf-fd92-498c-a5dc-a2fecc7af0d4.png)

Is there a faster solution than my procedure?

However, briefcase is a great tool! I had much more trouble with pyinstaller and its spooky hooks..

**Comment by freakboy3742** [comment] 2022-02-12 06:13
@monzelr Unfortunately, Windows is the platform that has the worst dev vs run experience. The runtime logs are effectively hidden unless you tweak the .lnk file. 

This is something we'd like to address - #620 is a ticket tracking the specific feature request. There's also #629 which should allow us to simplify the `build` step so that a full installer isn't required. This will, in turn, let us move the MSI build to the `package` step. It's entirely likely that the fix for the two are linked - we'll need to implement #629 in order to provide a good solution for #620.

**Comment by LandonGinn** [comment] 2022-02-18 01:13
I'd like to chime in here with a question. 
I found this to try and figure out why I cannot use briefcase run but I can with briefcase dev 
I am using the PySimpleGUI framework and it leverages tkinter. 
What exact steps must I take to get this to work? I am planning to package up for both windows and macOs

**Comment by freakboy3742** [comment] 2022-02-18 02:36
@LandonGinn In your case, the issue is the support package used by the packaged binary. We deliberately strip out Tkinter  on macOS because it *is* a GUI toolkit; and as such, any app using a different GUI toolkit doesn't need Tkinter as well.

If you want to support Tkinter in your own app, you'll need a custom build of the Python-Apple-support project that enables Tkinter support. This will generate a `Python-Apple-support.tar.gz` that you can include in your project by setting `support_package` in the Apple configuration section.

I'm not 100% certain about the state of Tkinter support on Windows as it's not my primary platform. On Windows, Briefcase uses the officially distributed embedded zipfile; you'll need to work out what is required to configure Tkinter with that binary.
