### ISSUE TITLE
MacOS app doesn't open, empty example is working

### ISSUE THREAD

**Issue by Noir-** [beeware/briefcase#579] opened 2021-03-14 18:10 UTC
I have an existing app made with PySide6 which I want to distribute using briefcase. For getting started I created an empty example using `briefcase new` and went through all steps until `briefcase run` was working. After that I started to merge my existing app into the structures briefcase created. I changed the dependency from PySide2 to PySide6 and added some more required packages into the TOML file.

I managed to make `briefcase dev` work after manually installing the dependencies except for PySide6 manually via pip into my venv. But when I try `briefcase run -u`, the app doesn't start. I don't get any error messages on the console.

Since the empty example is running, I assume that this isn't a problem with code signing. I don't know how I could get more information for debugging.

I'm on MacOS 10.15.7 (Catalina) with python 3.8.2 and briefcase 0.3.5. You can find the codebase in a comment below.

**Comment by Noir-** [comment] 2021-03-14 18:18
Small addition: I'm able to manually run the executable located in `AppName.app/Contents/MacOS/`without problems.

**Comment by Noir-** [comment] 2021-03-17 14:41
Here's the project in question: https://gitlab.com/klaustrophil/oxi-companion-briefcase

I'm still stuck with this problem... can anyone push me into the right direction?

**Comment by davidfokkema** [comment] 2021-05-19 09:09
I don't know if you're still interested in this, but I cloned your repository. To see crash logs of the packaged app, start the console app on MacOS, click start streaming, type (part of your) app name in the search field in the top right corner, press enter and select process instead of any. Then start your app. I got this:
```
error	11:04:33.726449+0200	OxiBriefcase	cannot open file at line 44595 of [02c344acea]
error	11:04:33.726511+0200	OxiBriefcase	os_unix.c:44595: (2) open(//oxi.db) - No such file or directory
default	11:04:33.726701+0200	OxiBriefcase	Traceback (most recent call last):
default	11:04:33.728583+0200	OxiBriefcase	    settings = SettingsManager()
default	11:04:33.728699+0200	OxiBriefcase	  File "/Users/david/tmp/oxi-companion-briefcase/macOS/app/OxiBriefcase/OxiBriefcase.app/Contents/Resources/app/oxibriefcase/SettingsManager.py", line 47, in __init__
default	11:04:33.728919+0200	OxiBriefcase	    self.__initialize_database()
default	11:04:33.729005+0200	OxiBriefcase	  File "/Users/david/tmp/oxi-companion-briefcase/macOS/app/OxiBriefcase/OxiBriefcase.app/Contents/Resources/app/oxibriefcase/SettingsManager.py", line 50, in __initialize_database
default	11:04:33.729259+0200	OxiBriefcase	    db_connection = sqlite3.connect(self.DB_FILE)
default	11:04:33.729396+0200	OxiBriefcase	sqlite3.OperationalError: unable to open database file
```
By adding some print statements you can try to figure out how the path name of your database is constructed. In dev mode, it might be in the current working directory, but in your packaged app, it might default to the root filesystem (which won't work).

**Comment by davidfokkema** [comment] 2021-05-19 09:12
This is not a bug in Briefcase, I believe. I suggest closing this issue and you can always ask for help in de the Discord channel which you can join at https://beeware.org/bee/chat/, or in the GitHub discussions forums at https://github.com/beeware/briefcase/discussions.

**Comment by freakboy3742** [comment] 2021-09-26 02:29
Closing on the basis that the issue seems to be an error in the app itself.

**Closed by freakboy3742** 2021-09-26 02:29 UTC
