### ISSUE TITLE
emulator fail: "Error: Package path is not valid"

### ISSUE THREAD

**Issue by shula** [beeware/briefcase#1893] opened 2024-07-02 19:34 UTC
### Describe the bug

`briefcase run android`  fails;

Otherwise the program running flawlessly.
error log attached

### Steps to reproduce

I followed the tutorial;
the only error was at:  `briefcase run android`

### Expected behavior

emulator showing up.  i saw it 2 years ago running from windows.

### Environment

- Operating System: win11
- Python version: 3.12
- Software versions:
  - briefcase:       0.3.19
  - Toga:  0.4.5
- java: "1.8.0_411"

### Logs

log is attached as file due to size
[briefcase.2024_07_02-22_11_24.run.log](https://github.com/user-attachments/files/16073483/briefcase.2024_07_02-22_11_24.run.log)

### Additional context

I recreated the environment (deleted everything and reinstalled)
I don't know how to read the logs, or =which "Package path" it referes to.

**Comment by rmartin16** [comment] 2024-07-02 19:58
The call to create the AVD for the emulator is failing because it can't find the requested system image. Normally, Briefcase will check if the system image already exists and if not, downloads it. In this case, Briefcase must be finding what it thinks is a system image....but the call to `avdmanager.bat` to actually create the AVD cannot find the system image.

What exists at the file path below?
```
C:\Users\user\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\system-images\android-31\default\x86_64
```

**Comment by shula** [comment] 2024-07-03 06:49
> The call to create the AVD for the emulator is failing because it can't find the requested system image. Normally, Briefcase will check if the system image already exists and if not, downloads it. In this case, Briefcase must be finding what it thinks is a system image....but the call to `avdmanager.bat` to actually create the AVD cannot find the system image.
> 
> What exists at the file path below?
> 
> ```
> C:\Users\user\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk\system-images\android-31\default\x86_64
> ```

it's mostly empty, and contains only a metadata file ".installData":

```
C:\Users\shumar\AppData\Local\BeeWare\briefcase\Cache\tools\android_sdk> **dir /s/b system-images**

...\system-images\android-31
...\system-images\android-31\default
...\system-images\android-31\default\x86_64
...\system-images\android-31\default\x86_64\.installer
...\system-images\android-31\default\x86_64\.installer\.installData
```

### The file ".installData" contains this:
```
  #Thu Jun 27 23:42:26 IDT 2024
  path=C\:\\Users\\user\\AppData\\Local\\BeeWare\\briefcase\\Cache\\tools\\android_sdk\\.temp\\PackageOperation01
class=com.android.repository.impl.installer.BasicInstaller
```

## other details (if it matters):

 - I remember from 2years ago, that directory `c:\Users\user\.android` was 8GB in size.

**And now:**

 -  `~\.android` is nearly empty (5k)
 - `~\.gradle` is 642MB (total)
 - c:\Users\user\AppData\Local\BeeWare\briefcase\Cache\tools - 1.8GB, full of sdks, java, etc.

**Comment by rmartin16** [comment] 2024-07-03 15:58
Yesterday, after I posted my original response, I concluded that the system image download must have failed the first time Briefcase tried to create an AVD. But this failure created the file system layout that Briefcase was looking for so in later Briefcase runs, it is concluding that the system image download must have been previously successful and moved on to attempting to create the AVD. However, the system image doesn't exist and AVD creation fails.

In your investigation above, you said running `sdkmanager.bat "system-images;android-31;default;x86_64"` was able to successfully download the system image. This is the exact same [command](https://github.com/beeware/briefcase/blob/580977d3d0e765e6a3a10ef1556305ed0d826170/src/briefcase/integrations/android_sdk.py#L768) that Briefcase runs to download the system image.

So, if my conclusions are correct, there is a hole in Briefcase's logic, either:
1) Briefcase should ensure the system image directory doesn't exist after a failure occurs during download/install
2) Briefcase should use an Android SDK-provided method to ensure the system image is actually installed

I'm leaning towards number 2; ideally this method would match what `avdmanager` does to check for a system image.

If you wanted to check, I would be curious if any of the log files created for your project contain the text:
```
Error while installing the 'system-images;android-31;default;x86_64' Android system image.
```
If so, that log file would show an attempt was made at one point to download the system image but it failed....and likely resulted in creating the filesystem layout with just the `.installData` file.

As for the `newemu` AVD....I don't really understand what's going on there...what is pointing at `d:\temp\android-user`??

**Comment by shula** [comment] 2024-07-03 16:28
- I erased and recreated my environment, so no logs (i checked anyway, but "Error while installing the" isn't there).

 - As for failure - I totally forgot:  The first time I ran "briefcase run android", I had to disconnect the network, and retried 2  days later.   So there was a failed partial attempt, indeed.

 - Yes, I am willing to go throught the same process again if that helps:
 I can completely erase beeware from my system, incl. mysterious `D:\temp\android-user`, .gridle, , .android, and the venv.
 
I searched now for environment vars containing either D:\TEMP or ANDROID-USER,  but i have neither (in or out the venv).

p.s. i'm going to flip to Linux OS next week,
so i experiements needed on Windows, that's better this weekend.

**Comment by rmartin16** [comment] 2024-07-03 16:43
> Yes, I am willing to go throught the same process again if that helps:

It would be good to know if the process works for you only using Briefcase. I created https://github.com/beeware/briefcase/issues/1895 for the system image issue; it'll be good to confirm there aren't other issues lurking that are preventing this working for you.

**Comment by freakboy3742** [comment] 2024-07-11 05:05
I'm going to close this on the basis that #1895 is (as far as we can establish) the underlying issue here, with a more concise description of the problem. Feel free to provide more details if you believe the issue is more than the "failed download" problem described by that new issue.

**Closed by freakboy3742** 2024-07-11 05:05 UTC
Labels: bug, android, awaiting details
