### ISSUE TITLE
Fix PySide6 Support on Linux

### ISSUE THREAD

**Issue by Tank-Missile** [beeware/briefcase#1032] opened 2023-01-04 04:54 UTC
### Describe the bug

Various packages are needed to avoid a segmentation fault from the built AppImage, especially xcb packages. The Dockerfile needs to be modified to add paths for linuxdeploy to find dependencies such as shiboken6 and QtWidgets. This can be done using a custom template, or using the dockerfile_extra_content option if you install from the latest master. Note that the built AppImage will not work on Ubuntu 18.04 despite being built on it.

```toml
system_requires = ["gstreamer1.0-gl", "libasound2", "libegl1", "libfontconfig1", "libgl1", "libnss3", "libpcsclite1", "libpulse0", "libwayland-cursor++0", "libxcb-icccm4", "libxcb-image0", "libxcb-keysyms1", "libxcb-randr0", "libxcb-render-util0", "libxcb-shape0", "libxcomposite1", "libxdamage1", "libxi6", "libxkbcommon-x11-0", "libxkbfile1", "libxrandr2", "libxtst6"]
dockerfile_extra_content = """
ENV APP_PACKAGES_PATH="/app/appimage/{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.AppDir/usr/app_packages"
ENV LD_LIBRARY_PATH="$APP_PACKAGES_PATH/shiboken6:$APP_PACKAGES_PATH/PySide6:$APP_PACKAGES_PATH/PySide6/Qt/lib"
"""
```
Official Qt6 binaries require at least glibc 2.28, but Ubuntu 18.04 uses glibc 2.27. AppImages can't be built with PySide newer than 6.2.4 on Ubuntu 18.04 because of this. If you want to use newer versions of Pyside, you will need to use a custom template with the base image set to at least Ubuntu 20.04. A newer support package is also needed because otherwise linuxdeploy will give a missing libffi.so.6 error.
```toml
support_package="cpython-3.10.9+20221220-x86_64-unknown-linux-gnu-install_only.tar.gz"
```

### Steps to reproduce

1. Generate a PySide6 project.
2. Create the docker image.
3. Build the AppImage.
4. Launch the AppImage from a terminal.
5. The AppImage may work on your system, but it won't on others due to missing xcb dependencies.

### Expected behavior

When generating a PySide6 project, you should not be required to add dependencies to system_requires and modify LD_LIBRARY_PATH just to make the AppImage not segfault. You should also not have to change the base image and the support package just to use newer versions of PySide6.

### Environment

- Operating System: Artix Linux
- Python version: 3.10.9
- Software versions:
  - Briefcase: 0.3.12.dev273+gdd565a1
  - PySide6: 6.4.1

**Comment by kushaldas** [comment] 2023-01-04 05:03
@Tank-Missile can you please tell me where to update the `support_package` value to try this out?

**Comment by Tank-Missile** [comment] 2023-01-04 05:04
@kushaldas pyproject.toml

**Comment by freakboy3742** [comment] 2023-01-04 05:57
Filling in some gaps here: There's an existing ticket (#947) dealing with making the base image configurable; the biggest impediment with adding more base images is the maintenance overhead on our side associated with publishing more base images. More automated tooling around management of support packages (or adopting a support package that isn't ubuntu-version-locked) would help here.

The `LD_LIBRARY_PATH` issue is an interesting one. We already traverse paths that contain .so files to pass to the `--deploy-deps-only` argument; it would be a fairly minor addition to add those paths to the Docker environment. There's a bigger question about whether we're using linuxdeploy correctly, though.

**Comment by kushaldas** [comment] 2023-01-11 13:08
I also had to exclude a library as suggested by internet, wrote them into additional_args for `linuxdeploy`.


```
"--exclude-library", "libxkbcommon"
```

**Comment by freakboy3742** [comment] 2023-04-15 03:28
An update - the situation for PySide support should now be better:

1. We now produce system packages by default, which don't have any of the sandboxing issues that AppImage is prone to.
2. The base linux distribution for an AppImage is now configurable to any ManyLinux base.

On that basis, I'm going to close this ticket, as the root cause (having a manylinux_2_28 base image for AppImage) is now resolved. I can't promise PySide6 support on AppImage is *that* much better - but that's due to AppImage, linuxdeploy, it's plugins, and how they work, rather than anything Briefcase is doing wrong. We've also provided a much more reliable alternative (system packages) as the default.

At this point, I suggest that any issues you're having with linuxdeploy building AppImages be passed upstream to that project. From the perspective of Briefcase, it's only a bug if we're using linuxdeploy incorrectly using their documented interface.

**Closed by freakboy3742** 2023-04-15 03:28 UTC
Labels: bug, linux
