### ISSUE TITLE
Linux AppImage not starting on Manjaro

### ISSUE THREAD

**Issue by annetracy** [beeware/briefcase#919] opened 2022-10-12 09:54 UTC
My rotate_video app runs successfully in dev mode (briefcase dev), 
it builds successfully (briefcase build), but fails to run (briefcase run)

I get the following message(s) I'm not even sure this is a Toga issue.
```
> [rotate_video] Built linux/Rotate_Video-0.0.1-x86_64.AppImage
(rotate_video-venv) tracy@daphne:~/Projects/RotateVideos/rotate_video$ briefcase run

[rotate_video] Starting app...

** (process:72473): WARNING **: 19:04:21.337: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libpango-1.0.so.0: undefined symbol: g_memdup2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_RotatecyrrfT/usr/app/rotate_video/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_RotatecyrrfT/usr/app/rotate_video/app.py", line 386, in main
    return Rotate_Video()
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga/app.py", line 278, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/libs/gtk.py", line 5, in <module>
    from gi.repository import Gtk, Gdk, GdkPixbuf, Gio, GLib, GObject  # noqa: F401, E402
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.15.72-1-MANJARO (64-bit)
Graphics Platform: X11

GTK2  V2.24.33
GTK3 V3.24.34

**Comment by annetracy** [comment] 2022-10-14 11:28
Yes I noticed those.

There may be a possibility that as GTK is installed to support GNOME apps on my KDE DE, my be causing a problem. The GNOME apps are not native to a KDE DE.

What about debs and flatpak, I noticed they were either under development of projected?

**Comment by freakboy3742** [comment] 2022-10-16 04:38
Flatpak has been implemented; `briefcase X linux flatpak` (for any command X) will generate a flatpak. Flatpaks tend to be harder to build if you have third-party binary library dependencies; but are more reliable when you have pure-python binaries  - or binaries that fit inside the umbrella that is supported out-of-the-box by Flatpak. Unfortunately, it's difficult to quantify what that umbrella covers, other than "normal GTK desktop stuff", as the contents of the flatpak base image is somewhat opaque.

We haven't got support for debs at this time.

**Comment by annetracy** [comment] 2022-10-16 05:21
Is there any reason you chose to ignore KDE, or rather the Qt toolkit. Personally I think QT is much easier to work with. I've certainly found building QtPython apps much easier to write than GTK Python apps, and what the KDE devs have achieved leaves GNOME in the dust IMO.

Although Toga does make wotking with GTK a doddle.

I've installed a GNOME desktop (Ubuntu) on a VM, so GTK native, and am building the app on that, to see if there is any difference.

**Comment by freakboy3742** [comment] 2022-10-16 11:59
We haven't "ignored" Qt and KDE. We've made a choice to focus our limited resources. 

Briefcase *does* provide support for Qt - it provides both PySide2 and Pyside6 templates for apps.
 
When it comes to Toga, we've focused our development effort on the GUI framework on GTK, as it is the GUI toolkit that drives the default desktop option on most of the popular Linux distributions (Ubuntu, Debian, Fedora, CentOS, and Raspbian, amongst others).

However, if you poke around the Toga repository, you'll find beeware/toga#1142, where we've confirmed that we'd be happy to provide native Qt support - we just need someone to contribute it. There is already a [stub project in the Toga nursery](https://github.com/beeware/toga/tree/main/nursery/qt). All that is missing is an implementation.

If this is an area where you're interested in contributing, then I'd encourage you to start there.

**Comment by annetracy** [comment] 2022-10-16 23:57
I was just wondering, thanks.

OK here's the thing.

I've been able to get libcanberra to install, and it loads, by adding a reference to it in the pyproject.toml file

`[tool.briefcase.app.rotate_video.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
    'gir1.2-xapp-*',
    'libxapp-*',
    'libcanberra-gtk*',
]`

I added the following lines...

`    'gir1.2-xapp-*',
    'libxapp-*',
    'libcanberra-gtk*',`

However, while it appears that all three libraries are installed, I still get the error.

`Gtk-Message: 09:54:30.220: Failed to load module "xapp-gtk3-module"
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
Gtk-Message: 09:54:30.526: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 09:54:30.580: Failed to load module "colorreload-gtk-module"`

As far as i can tell the issue revolves around libxapp.

I will hopefully narrow this down.

I will also try to upload the log file.

**Comment by annetracy** [comment] 2022-10-17 00:06
[briefcase.2022_10_17-09_35_03.run.log](https://github.com/beeware/briefcase/files/9795980/briefcase.2022_10_17-09_35_03.run.log)

**Comment by annetracy** [comment] 2022-10-31 04:32
Sorry I haven't been in for a while. I've been trying to locate a second hand laptop that I could afford... I'm a pensioner and all that.

So I installed Ubuntu 20.04 on the second Laptop, the app builds, and runs correctly on the GNOME desktop. But if the theme is changed, the app has to be restarted to reflect the changed desktop theme.
 
The app also runs correctly on Manjaro KDE, but fails to follow the desktop theme.

**Comment by annetracy** [comment] 2022-10-31 21:03
Ok. I've built the app on my Manjaro KDE system, transfered the resulting appimage to the Ubuntu system,  the app runs correctly, and follows the desktop theme.

If I run the app from a terminal on my Manjaro KDE system, it ignores the desktop Theme, and I get the errors, I had assumed were related to the build

`Gtk-Message: 06:53:04.789: Failed to load module "xapp-gtk3-module"
Gtk-Message: 06:53:04.793: Failed to load module "canberra-gtk-module"
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
Gtk-Message: 06:53:05.609: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 06:53:05.617: Failed to load module "colorreload-gtk-module"`

This I now believe is related to running a GTK app on KDE, or possibly, specifically to Manjaro KDE.

Recently a poster on the Manjaro Forum posted a similar set of errors, related to running a Flatpak on a Manjaro KDE system

I will install KUbuntu on the spare laptop, to confirm if this is GTK/KDE related or specificaly Manjaro KDE

**Comment by freakboy3742** [comment] 2022-10-31 22:38
It would also be helpful to confirm if the "ignoring desktop theme" problem is a bug or a "feature". I completely agree that it isn't what most users would expect - but based on what I know of how AppImage works, I can't see how it would be possible for an AppImage to reliably adopt the end-user's theme. 

AppImage works by bundling every binary needed to run an app, outside of a very small core set of libraries (essentially libc and not much else). The distributed app is very using a copy of any GUI libraries, on the basis that there's no way to guarantee that the end-user's computer will have the GUI framework that you require. 

If my understanding is correct, I don't see how it would be possible for an app to use a bundled version of GTK, but *not* use a bundled version of the GTK theme - if only because there's no way to guarantee the end-user's theme (assuming they have one) will be compatible with the bundled version of GTK. 

So - it would be helpful for you to confirm if this "theme ignoring" behavior is common to *all* AppImage apps. There's a collection of AppImage apps on [this website](https://appimage.github.io) - do those apps follow the system theme, or do you see the same problem?

**Comment by annetracy** [comment] 2022-10-31 22:47
I'll check that out.

**Comment by annetracy** [comment] 2022-11-01 00:52
Interesting...

I just changed the GTK3 theme setting from Breeze to Adwaita-Dark... the KDE theme is Breath-Dark.

The default Theme for Manjaro KDE is Breath, while the default Theme for GTK3 is Breeze.

Now, on the Kubuntu system the default setting for KDE is Breeze, as is the default setting for GTK3

this means the GTK3 appimage is theming correctly, in spite of those errors.

changing Kubuntu Theme to Breeze Dark for both KDE and GTK3 results in a correctly themed appimage.


So, now I can theme both KDE and GTK3 apps to more or less the same theme on Manjaro KDE... KDE theme Breath-Dark, and GTK3 Adwaita-Dark, and the appimage picks up the GTK3 theme.

and on the Kubuntu system I can set KDE to Breeze-Dark and GTK3 to Breeze-Dark, and the appimage correctly picks up the GTK3 theme.

Sorry this appears to have been a bit of a wild Goose chase. The biggest problem seems to be there is no comparable Breath Theme for GTK apps on Manjaro KDE, whereas the older Breeze Theme is available on Kubuntu.

**Comment by freakboy3742** [comment] 2022-11-01 01:58
No worries about the goose chase - app packaging issues are 99% goose by volume :-)

To clarify where we are at, if I'm following correctly:
1. The originally reported problem (the app not starting at all) has been resolved, as long as `'gir1.2-xapp-*', 'libxapp-*', 'libcanberra-gtk*'` is added to the system requires when the app is built.
2. The theming issue is largely down to whether the system where the app is running has thethemes available/installed

If that's the case, it sounds like there's not much we can do with 92); but for (1) we can add the extra required system libraries to the base [briefcase-template](https://github.com/beeware/briefcase-template) so that every new project gets those installed by default. It would be preferable if we can narrow those packages down to specific versions, rather than wildcards; from a quick inspection of the packages installed by the wildcards, there's a lot of extra stuff being installed, not just 3 extra packages, and it's not immediately obvious to me why some of them are needed. If they are, that's fine - but I'd rather be explicit about those requirements.

**Comment by annetracy** [comment] 2022-11-01 02:23
No I think one was solved by adding

`'DEPLOY_GTK_VERSION=3 gtk',`

Which was missing. Ensuring that that is indeed in the .toml means the app will build and run.

The errors related to `'gir1.2-xapp-*', 'libxapp-*', 'libcanberra-gtk*'` don't appear to affect functionality, and when issue (2) is accounted for, by selecting a GTK3  theme that is comparable to the current non GTK/GNOME DE theme, those errors seem irrelevant.

I've just installed snap that is built on GTK3, and it exhibits the same 'issues', and runs correctly, and with my GTK3 Theme choice fits my KDE theme.

But yes (2) is basically DE and Theme dependant 

A lot of my running around in circles was related to my lack of understanding of how Appimage/Flatpak/Snaps work.

**Comment by freakboy3742** [comment] 2022-11-01 02:30
Ok - in which case, can we close this issue as resolved? AFAICT, `DEPLOY_GTK_VERSION=3 gtk` will be included, as long as you're using a recent version of Briefcase; it won't be added automatically to an existing project, but there isn't much we can do about that.

**Comment by annetracy** [comment] 2022-11-01 03:05
yes please close.

I'll do some research, and probably look at the QT stub.

**Closed** 2022-11-01 03:06 UTC
Labels: bug, up-for-grabs, linux
