### ISSUE TITLE
Can't generate new application

### ISSUE THREAD

**Issue by chrimoe** [beeware/briefcase#549] opened 2020-12-28 17:11 UTC
briefcase is properly installed
The following issue occured after I have startet briefcase new in a venv:
Generating a new application 'Hello World'
Using existing template (sha 4cae126120eed600efd762a1b00ec5d901c422c9, updated Sat Oct 17 08:26:22 2020)
Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
Stopping generation because pre_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\briefcase.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\briefcase\__main__.py", line 11, in main
    command(**options)
  File "c:\programdata\anaconda3\lib\site-packages\briefcase\commands\new.py", line 523, in __call__
    state = self.new_app(template=template, **options)
  File "c:\programdata\anaconda3\lib\site-packages\briefcase\commands\new.py", line 489, in new_app
    extra_context=context
  File "c:\programdata\anaconda3\lib\site-packages\cookiecutter\main.py", line 106, in cookiecutter
    output_dir=output_dir,
  File "c:\programdata\anaconda3\lib\site-packages\cookiecutter\generate.py", line 294, in generate_files
    repo_dir, 'pre_gen_project', project_dir, context, delete_project_on_failure
  File "c:\programdata\anaconda3\lib\site-packages\cookiecutter\generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "c:\programdata\anaconda3\lib\site-packages\cookiecutter\hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "c:\programdata\anaconda3\lib\site-packages\cookiecutter\hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "c:\programdata\anaconda3\lib\site-packages\cookiecutter\hooks.py", line 87, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)

what goes wrong?

**Comment by freakboy3742** [comment] 2020-12-30 00:16
Thanks for the report - this isn't an error I've seen before. It appears to be a failure during generation of the app template, but it's very difficult to diagnose beyond that because you haven't provided any of the details we asked for.

When you opened this ticket, you should have been presented with a template for a bug report that includes the details we need. Without those details, it's almost impossible for us to diagnose, because we don't know what it is that you were trying to do when you generated the bug:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment:**
 - Operating System:
 - Python version:
 - Software versions:
   - Briefcase:
   - Toga:
   - ...

**Additional context**
Add any other context about the problem here.

**Comment by freakboy3742** [comment] 2021-09-26 02:18
Closing on the basis that the requested details have not been provided.

**Closed by freakboy3742** 2021-09-26 02:18 UTC
Labels: bug, more-details
