### ISSUE TITLE
Application crashes when serving mp4 files

### ISSUE THREAD

**Issue by werwolf2303** [beeware/briefcase#1941] opened 2024-08-06 22:05 UTC
### Describe the bug

When I use this code to serve mp4 files using cherrypy
```python
import http
from socketserver import BaseServer
from typing import Iterable
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, CENTER, ROW
import os
import threading
from urllib.parse import unquote
import random
import socketserver
import mimetypes
import socket
from http.server import BaseHTTPRequestHandler, HTTPServer
import cherrypy

class VideoView(toga.Box):
    def __init__(self, paths, mainLoop, id: str | None = None, style=Pack(flex=1), children: Iterable[toga.Widget] | None = None):
        super().__init__(id, style, children)
        self.paths = paths
        self.mainLoop = mainLoop
        self.thread = threading.Thread(target=self.startServer)
        self.thread.start()
        self.createView()

    def startServer(self):
        PATH = self.paths.data
        class Root(object): pass
        cherrypy.tree.mount(Root(), '/', config={
            '/': {
                'tools.staticdir.on': True,
                'tools.staticdir.dir': PATH,
                'tools.staticdir.index': '',
            },
        })
        self.find_free_port()
        cherrypy.config.update({'server.socket_port': self.port})
        print("Port: " + str(self.port)) 
        self.mainLoop.call_later(0.1, cherrypy.engine.start)

    def find_free_port(self):
        port = random.randint(1024, 65535)
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            result = sock.connect_ex(("localhost", port))
            if(result != 0):
                self.port = port
            sock.close()

    def loadVideo(self, url):
        self.videoView.evaluate_javascript("loadVideo('" + "http://127.0.0.1:" + str(self.port) + "/" + str(url) + "')")
        pass

    def createView(self):
        self.videoView = toga.WebView(style=Pack(flex=1))
        with open(os.path.join(self.paths.app, "resources/viewer.html"), "r") as file:
            self.videoView.set_content("", file.read().replace("\n", ""))
        self.add(self.videoView)
```

It just crashes the entire application without any exception. 

### Steps to reproduce

1. Start application
2. Try opening the video in a browser
3. Crash

### Expected behavior

Content is served and application keeps running

### Environment

- Operating System: MacOS
- Python version: 3.12.4
- Software versions:
  - Briefcase: 0.13.9
  - Toga: 0.4.5
  - Newest of every dependency

### Logs

Too Big

[REDACTED]

### Additional context

I am using a MacOS virtual machine and I have already determined that the vm is not the cause because the code runs fine without beeware

**Comment by freakboy3742** [comment] 2024-08-06 22:54
It isn't clear to me that this a bug with Briefcase.

* Your instruction to try opening "the" video... will depend, at least in part, on the video in question - but... I *really* don't want you to share that, and I think you know why. Side note - you may want to consider redacting your logs before you share them. 
* You say you're using "macOS"... but what version? The logs suggest macOS 10.15, on an Intel Mac; if that's the case, then that's not a version of macOS that Toga supports.
* You say you're using Briefcase "0.13.9"... I presume that's a typo, because that isn't a valid Briefcase version.
* "Newest of every dependency" isn't helpful - we need to know exactly what your dependencies *are*, so that *we* can reproduce the problem

If the app is generating a hard crash, and you'll need to share details of that crash - that won't be in the form of a Python stack trace, it will be the contents of the "Application has crashed" window that the operating system generates.

I'm going to close this ticket - partially on the basis that it isn't actionable, partially on the basis that it's likely not a Briefcase problem (after all - Briefcase is just packaging the app); but also because the content being surfaced in the logs associated with this issue isn't appropriate for sharing in a public forum. 

If you'd like help narrowing down a problem, I'd suggest opening a [discussion topic](https://github.com/beeware/briefcase/discussions). In that, we need a clear *and complete* set of reproduction instructions, including a *full* set of materials that can be used to reproduce the problem - redacted such that is it is appropriate for a wider audience.

**Closed by freakboy3742** 2024-08-06 22:54 UTC
Labels: bug
