### ISSUE TITLE
Changing default configuration directory path to standard location

### ISSUE THREAD

**Issue by jtrakk** [beeware/briefcase#430] opened 2020-06-22 20:01 UTC
Currently briefcase uses `~/.briefcase/` for saving configuration by default.

Some people, myself included, don't like the clutter and lag (especially on less-expensive hardware) caused by having large numbers of files in user home. The popular FreeDesktop standard [specifies](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) a preferred location:

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

Using this standardized location also means that there's one obvious place to look for each type of file (config, data, cache), which is a nice consistency for users like me so I don't have to remember a different location for each application.

Would the Briefcase project be willing to conform to this standard by default?

To help developers find the right location on different platforms, the tiny but widely used [`appdirs` module](https://pypi.org/project/appdirs/) provides a simple interface to the configuration, data, and cache directories.

**Comment by freakboy3742** [comment] 2020-06-22 22:28
Closing as a duplicate of #374. In short; yes, we'd be in favour of adopting the FreeDesktop specification.

**Closed by freakboy3742** 2020-06-22 22:28 UTC
Labels: duplicate
