### ISSUE TITLE
Understanding the error with UIApplicationMain(argc, argv, nil, @"PythonAppDelegate");

### ISSUE THREAD

**Issue by ianc89** [beeware/briefcase#614] opened 2021-09-02 11:15 UTC
Hi, I am looking for a new way to produce casual apps that allows me to release on Android and iOS. I have some familiarity with Swift but none with Java. This project seems super useful in that regard (as I have a lot of experience with python).

I have been following the initial tutorial and I was very pleased to see that the simple app would run in the iPhone simulator. I decided to explore a bit the Xcode workspace, and could run on the simulator from there too. However, when I attempt to load it onto my iPhone, I encounter a crash.

The following line is the issue, and while there is some detail about objective-c in the code where it crashes (main.m), I am unable to find some information to explain what is missing, or what I should be adding.
`UIApplicationMain(argc, argv, nil, @"PythonAppDelegate");`
`Thread 1: EXC_BAD_ACCESS (code=2, address=0x103f57e08)`

I should note that the build succeeds, it is the running that crashes.

Are there any tutorials to explain what is missing to allow this simple app to be built and run on a real device? This is quite a limitation, but I also do not understand why the simulator works, but not the real device.

**To Reproduce**
Follow the tutorial, load the workspace in Xcode, and run on a device.

**Expected behavior**
I had expected that the behaviour on the simulator would cross over to a real device.

**Environment:**
 - Operating System: Big Sur 11.4
 - Python version: 3.9 (all packages installed today)
 
 **Additional context**
I apologise if this is a known limitation, or if I missed something. While briefcase cannot deploy yet, my thought was that if I can take the builds it provides, I could handle deployment by hand.

**Comment by freakboy3742** [comment] 2022-03-28 02:47
Apologies for the delayed response; this appears to be caused by beeware/Python-Apple-support#131. Closing this ticket since it's not inherently a problem with Briefcase; follow the ticket on the support repository for further updates.

**Closed by freakboy3742** 2022-03-28 02:47 UTC
Labels: bug
