### ISSUE TITLE
Unable to link app during briefcase package

### ISSUE THREAD

**Issue by durgaswaroop** [beeware/briefcase#530] opened 2020-11-10 17:37 UTC
**Describe the bug**
I am going through the tutorials. I have created the Hello World app on Windows and verified that it works when I do
`briefcase dev`.  Then I went through the next steps to package the application. 
I ran the `briefcase package` and I got the following error.
```
Linking application installer...
light.exe : error LGHT0103 : The system cannot find the file 'src\python\_multiprocessing.pyd' with type ''.

Unable to link app helloworld.
```

The file `src\python\_multiprocessing.pyd` exists in the `windows\Hello World` directory.

The full output is as follows:

```
[helloworld] Building MSI...

Compiling application manifest...

Compiling application installer...
helloworld.wxs
helloworld-manifest.wxs

Linking application installer...
light.exe : error LGHT0103 : The system cannot find the file 'src\python\_multiprocessing.pyd' with type ''.

Unable to link app helloworld.
```

**To Reproduce**
Follow the tutorial steps on Windows 10 machine and run `briefcase package` command. 

**Expected behavior**
The installer is supposed to be created. 

**Environment:**
 - Operating System: Windows 10 64 bit
 - Python version: Python 3.8 32 bit
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: Not sure

Please let me know how I can fix this

**Comment by freakboy3742** [comment] 2023-04-15 03:48
Closing as a duplicate of #948.

**Closed by freakboy3742** 2023-04-15 03:48 UTC
Labels: bug, documentation, windows
