### ISSUE TITLE
Tutorial 1, part 1 - fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by imagescape** [beeware/briefcase#191] opened 2019-02-08 20:17 UTC
I'm following your tutorial on Ubuntu 16.04. All dependencies are met. However, at https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-1.html

I put the indicated code into "app.py", then `$ python setup.py linux -s`

but get the following (see below). Note that the app "starts" in that I get a window with the title "Converter", but there is nothing inside it. It's just a blank white rectangle. Any help would me much appreciated. Thank you.

*********

running linux

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-gtk==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11)
Collecting toga-core==0.3.0.dev11 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11)
Collecting gbulb>=0.5.3 (from toga-gtk==0.3.0.dev11)
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: pycairo, travertino, toga-core, pygobject, gbulb, toga-gtk
Successfully installed gbulb-0.6.1 pycairo-1.18.0 pygobject-3.30.4 toga-core-0.3.0.dev11 toga-gtk-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /home/&lt;my-username&gt;/sites/beeware/helloworld
Building wheels for collected packages: helloworld
  Building wheel for helloworld (setup.py) ... ^[[?25ldone
^[[?25h  Stored in directory: /tmp/pip-ephem-wheel-cache-m9f_4wto/wheels/69/ae/76/d31f6f3a1228ddd10fe2d01ff2cffa6a3920b4a21d0ca0f200
Successfully built helloworld
Installing collected packages: helloworld
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Hello World
Traceback (most recent call last):
  File "/home/&lt;my-username&gt;/sites/beeware/helloworld/linux/app_packages/toga_gtk/app.py", line 71, in startup
    self.interface.startup()
  File "/home/&lt;my-username&gt;/sites/beeware/helloworld/linux/app_packages/toga/app.py", line 179, in startup
    self.main_window.show()
  File "/home/&lt;my-username&gt;/sites/beeware/helloworld/linux/app_packages/toga/window.py", line 166, in show
    self._impl.show()
  File "/home/&lt;my-username&gt;/sites/beeware/helloworld/linux/app_packages/toga_gtk/window.py", line 101, in show
    self.interface.content._impl.rehint()
AttributeError: 'NoneType' object has no attribute '_impl'

App started.

**Comment by freakboy3742** [comment] 2019-02-09 13:55
Thanks for the report - the "no attribute _impl" error suggests that the content hasn't been assigned to the window - but assuming you haven't made any errors copying the sample code, I'm not sure why that would be happening in this case. I haven't had any luck reproducing that error on my test setup.

A couple of possible diagnostic details:
* Do you get the same behavior if you manually start the app, rather than using the `-s` flag? There should be a linux/Converter script generated by briefcase; does that give the same behavior?
* What about starting the app *without* briefcase? If you run `python -m Converter`, do you get the same errors?
* You're using Ubuntu 16.04 - is there anything custom about your GUI setup? Is it a stock GTK install with the default GUI, or are you using anything custom?

**Comment by freakboy3742** [comment] 2019-12-21 01:20
Closing due to lack of response from the reporter.

**Closed by freakboy3742** 2019-12-21 01:20 UTC
