### ISSUE TITLE
Hello World Tutorial "Unable to install ..." Error

### ISSUE THREAD

**Issue by hlovatt** [beeware/briefcase#300] opened 2020-02-06 06:19 UTC
Hi,

When trying to run the Hello World Tutorial in the iPhone simulator I get:

Targeting an iPhone 11 running iOS 13.3 (device UDID DAB73158-E68C-4A8A-B183-F9C4E40F16AF)
Booting iPhone 11 simulator running iOS 13.3...
Opening iPhone 11 simulator running iOS 13.3...
[helloworld] Uninstalling old app version...
[helloworld] Installing new app version...
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not install at this time.
Failed to chmod /Users/lov080/Library/Developer/CoreSimulator/Devices/DAB73158-E68C-4A8A-B183-F9C4E40F16AF/data/Bundle/Application/D531A5A2-568D-4947-824B-486C0DC5CA39/Hello World.app/Hello World : No such file or directory
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/lov080/Library/Developer/CoreSimulator/Devices/DAB73158-E68C-4A8A-B183-F9C4E40F16AF/data/Bundle/Application/D531A5A2-568D-4947-824B-486C0DC5CA39/Hello World.app/Hello World : No such file or directory
Unable to install new version of app helloworld.

The problem is that the directory D531A5A2-568D-4947-824B-486C0DC5CA39 doesn't exist.

Any suggestions of why it fails?

**Comment by hlovatt** [comment] 2020-02-06 06:22
This may or may not be relevant but when building the App I did get some warnings:

warning: 'UILaunchImages' has been deprecated, use launch storyboards instead. (in target 'Hello World' from project 'Hello World')
note: Using new build system
note: Planning build
note: Constructing build description
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Hello World editor. (in target 'Hello World' from project 'Hello World')
warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e). (in target 'Hello World' from project 'Hello World')
Build succeeded.

However it did report that the App was built (last line of above).

**Comment by freakboy3742** [comment] 2020-02-06 06:59
Thanks for the report! 

The "UILaunchImages" bug is a red herring - that's something that was introduced in iOS13 that they're slowly deprecating. We need to modify the iOS app template to use the new format, but we've got some time before that becomes critical.

However, the rest of the error message, about "none of the architectures in ARCH" *does* point at the problem. We only recently added a specific architecture setting in the project configuration file; looks like we missed one of the required architectures in our testing.

I've just pushed an update to the template which should correct the problem. If you delete your project's iOS directory (or run `briefcase create iOS` again), you should have more luck. Let me know if it works for you.

**Comment by hlovatt** [comment] 2020-02-06 23:02
Without doing anything "briefcase create iOS" fails:

OSError: [Errno 66] Directory not empty: '/Users/lov080/Google Drive/Python/BeeWare/examples/beeware-tutorial/helloworld/iOS/Hello World'

However if I manually delete iOS folder then:

create
build
run

it all works now - thanks.

**Comment by freakboy3742** [comment] 2020-02-07 01:24
Thanks for letting us know. Calling `create iOS` a second time *should* warn that the directory already exists and offer to remove it; so that's possibly a bug. 

However, I'm not able to reproduce the problem. If I use `briefcase run iOS` to build and runwith the old, "bad" template, I get an iOS folder, but the launch fails in the way you describe.
```
(venv) lassiter:helloworld rkm$ briefcase run ios
...
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not install at this time.
Failed to chmod /Users/rkm/Library/Developer/CoreSimulator/Devices/4768AA69-497B-4B37-BD0C-3961756C38AC/data/Bundle/Application/D01E8301-3182-4C0F-B525-C6F30F07F3C7/Hello World.app/Hello World : No such file or directory
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/rkm/Library/Developer/CoreSimulator/Devices/4768AA69-497B-4B37-BD0C-3961756C38AC/data/Bundle/Application/D01E8301-3182-4C0F-B525-C6F30F07F3C7/Hello World.app/Hello World : No such file or directory
Unable to install new version of app helloworld.

(venv) lassiter:helloworld rkm$ ls
LICENSE		README.rst	iOS		pyproject.toml	src
```
However, if I then issue a `briefcase create ios` using the "fixed" template, I get prompted to delete the project:
```
(venv) lassiter:helloworld rkm$ briefcase create ios

Application helloworld already exists; overwrite (y/N)?
```
Are you able to clarify what (if anything) you did differently? The existence of the iOS folder *should* be all that is needed to trigger the "already exists" prompt, so it's interesting that you didn't see it.

**Comment by hlovatt** [comment] 2020-02-07 02:56
This is what I did:

```
(beeware-venv) lov080@DARKZERO-LN helloworld % briefcase create iOS            

Application helloworld already exists; overwrite (y/N)? y

[helloworld] Removing old application bundle...
Traceback (most recent call last):
  File "/Users/lov080/Google Drive/Python/BeeWare/examples/beeware-tutorial/beeware-venv/bin/briefcase", line 12, in <module>
    sys.exit(main())
  File "/Users/lov080/Google Drive/Python/BeeWare/examples/beeware-tutorial/beeware-venv/lib/python3.8/site-packages/briefcase/__main__.py", line 11, in main
    command(**options)
  File "/Users/lov080/Google Drive/Python/BeeWare/examples/beeware-tutorial/beeware-venv/lib/python3.8/site-packages/briefcase/commands/create.py", line 610, in __call__
    state = self.create_app(app, **full_kwargs(state, kwargs))
  File "/Users/lov080/Google Drive/Python/BeeWare/examples/beeware-tutorial/beeware-venv/lib/python3.8/site-packages/briefcase/commands/create.py", line 564, in create_app
    self.shutil.rmtree(str(bundle_path))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 730, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 612, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 610, in _rmtree_unsafe
    os.rmdir(path)
OSError: [Errno 66] Directory not empty: '/Users/lov080/Google Drive/Python/BeeWare/examples/beeware-tutorial/helloworld/iOS/Hello World'

```
As you can see it failed.

Then I did:

`(beeware-venv) lov080@DARKZERO-LN helloworld % rm -r iOS`

Then:

```
(beeware-venv) lov080@DARKZERO-LN helloworld % briefcase create iOS

[helloworld] Generating application template...
Using app template: https://github.com/beeware/briefcase-iOS-Xcode-template.git
Using existing template (sha 58bebcabf52b163c77f455ac2816e53b1f5169b6, updated Thu Feb  6 14:55:19 2020)

[helloworld] Installing support package...
Using support package https://briefcase-support.org/python?platform=iOS&version=3.8
Python-3.8-iOS-support.b1.tar.gz already downloaded
Unpacking support package...

[helloworld] Installing dependencies...
Collecting toga-iOS>=0.3.0.dev18
  Using cached toga_iOS-0.3.0.dev18-py3-none-any.whl (32 kB)
Collecting toga-core==0.3.0.dev18
  Using cached toga_core-0.3.0.dev18-py3-none-any.whl (512 kB)
Collecting rubicon-objc>=0.3.0
  Using cached rubicon_objc-0.3.1-py2.py3-none-any.whl (66 kB)
Collecting travertino>=0.1.0
  Using cached travertino-0.1.2-py3-none-any.whl (15 kB)
Installing collected packages: travertino, toga-core, rubicon-objc, toga-iOS
Successfully installed rubicon-objc-0.3.1 toga-core-0.3.0.dev18 toga-iOS-0.3.0.dev18 travertino-0.1.2

[helloworld] Installing application code...
Installing src/helloworld...

[helloworld] Installing application resources...
Unable to find src/helloworld/resources/helloworld-20.png for 20px application icon; using default
Unable to find src/helloworld/resources/helloworld-29.png for 29px application icon; using default
Unable to find src/helloworld/resources/helloworld-40.png for 40px application icon; using default
Unable to find src/helloworld/resources/helloworld-58.png for 58px application icon; using default
Unable to find src/helloworld/resources/helloworld-60.png for 60px application icon; using default
Unable to find src/helloworld/resources/helloworld-76.png for 76px application icon; using default
Unable to find src/helloworld/resources/helloworld-80.png for 80px application icon; using default
Unable to find src/helloworld/resources/helloworld-87.png for 87px application icon; using default
Unable to find src/helloworld/resources/helloworld-120.png for 120px application icon; using default
Unable to find src/helloworld/resources/helloworld-152.png for 152px application icon; using default
Unable to find src/helloworld/resources/helloworld-167.png for 167px application icon; using default
Unable to find src/helloworld/resources/helloworld-180.png for 180px application icon; using default
Unable to find src/helloworld/resources/helloworld-1024.png for 1024px application icon; using default

[helloworld] Created iOS/Hello World
```

This time it worked and subsequently `build` and `run` also worked.

If I run `create` again now:

```
(beeware-venv) lov080@DARKZERO-LN helloworld % briefcase create iOS

Application helloworld already exists; overwrite (y/N)? y

[helloworld] Removing old application bundle...

[helloworld] Generating application template...
Using app template: https://github.com/beeware/briefcase-iOS-Xcode-template.git
Using existing template (sha 58bebcabf52b163c77f455ac2816e53b1f5169b6, updated Thu Feb  6 14:55:19 2020)

[helloworld] Installing support package...
Using support package https://briefcase-support.org/python?platform=iOS&version=3.8
Python-3.8-iOS-support.b1.tar.gz already downloaded
Unpacking support package...

[helloworld] Installing dependencies...
Collecting toga-iOS>=0.3.0.dev18
  Using cached toga_iOS-0.3.0.dev18-py3-none-any.whl (32 kB)
Collecting toga-core==0.3.0.dev18
  Using cached toga_core-0.3.0.dev18-py3-none-any.whl (512 kB)
Collecting rubicon-objc>=0.3.0
  Using cached rubicon_objc-0.3.1-py2.py3-none-any.whl (66 kB)
Collecting travertino>=0.1.0
  Using cached travertino-0.1.2-py3-none-any.whl (15 kB)
Installing collected packages: travertino, toga-core, rubicon-objc, toga-iOS
Successfully installed rubicon-objc-0.3.1 toga-core-0.3.0.dev18 toga-iOS-0.3.0.dev18 travertino-0.1.2

[helloworld] Installing application code...
Installing src/helloworld...

[helloworld] Installing application resources...
Unable to find src/helloworld/resources/helloworld-20.png for 20px application icon; using default
Unable to find src/helloworld/resources/helloworld-29.png for 29px application icon; using default
Unable to find src/helloworld/resources/helloworld-40.png for 40px application icon; using default
Unable to find src/helloworld/resources/helloworld-58.png for 58px application icon; using default
Unable to find src/helloworld/resources/helloworld-60.png for 60px application icon; using default
Unable to find src/helloworld/resources/helloworld-76.png for 76px application icon; using default
Unable to find src/helloworld/resources/helloworld-80.png for 80px application icon; using default
Unable to find src/helloworld/resources/helloworld-87.png for 87px application icon; using default
Unable to find src/helloworld/resources/helloworld-120.png for 120px application icon; using default
Unable to find src/helloworld/resources/helloworld-152.png for 152px application icon; using default
Unable to find src/helloworld/resources/helloworld-167.png for 167px application icon; using default
Unable to find src/helloworld/resources/helloworld-180.png for 180px application icon; using default
Unable to find src/helloworld/resources/helloworld-1024.png for 1024px application icon; using default

[helloworld] Created iOS/Hello World

```
It works, including `build` and `run`.

So strange that it didn't work 1st time without a manual delete, can't explain that.

**Comment by freakboy3742** [comment] 2020-02-07 03:00
Interesting - it looks like you were prompted to delete, but the delete failed for some reason. Is it possible you had an editor open on a file in the iOS directory, or a terminal session open with that folder as the current working directory? I'm guessing something like that prevented the delete, but `rm -rf iOS` forced the deletion.

Regardless, this is definitely an error case we should catch and report in a more helpful fashion.

**Comment by hlovatt** [comment] 2020-02-07 03:06
Yeah you are probably right, I could have had something looking at that folder. 

When I did `rm` I didn't use the `f` flag and it didn't complain, but maybe in trying to debug I changed something (can't think what though - don't think I had an editor/finder/terminal pointing at that directory).

**Comment by freakboy3742** [comment] 2020-05-10 03:20
The history of this ticket makes it a little difficult to find the actual problem that needs to be fixed. Since this is a good candidate for a first time contributor to fix, I'm going to close this ticket in favor of #394, which lays out the issue in more clarity.

**Closed by freakboy3742** 2020-05-10 03:20 UTC
Labels: bug
