### ISSUE TITLE
Error on briefcase dev for helloworld

### ISSUE THREAD

**Issue by tubbadu** [beeware/briefcase#686] opened 2022-03-22 20:26 UTC
**Describe the bug**
running `briefcase dev` returns this error:

```
[helloworld] Installing dependencies...
Collecting toga-gtk>=0.3.0.dev32
Using cached toga_gtk-0.3.0.dev32-py3-none-any.whl (50 kB)
Collecting pygobject>=3.14.0
Using cached PyGObject-3.42.0.tar.gz (716 kB)
Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> [45 lines of output]
Collecting setuptools
Using cached setuptools-60.10.0-py3-none-any.whl (1.1 MB)
Collecting wheel
Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting pycairo
Using cached pycairo-1.21.0.tar.gz (340 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pycairo
Building wheel for pycairo (pyproject.toml): started
Building wheel for pycairo (pyproject.toml): finished with status 'error'
error: subprocess-exited-with-error

× Building wheel for pycairo (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [19 lines of output]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/cairo
copying cairo/__init__.py -> build/lib.linux-x86_64-3.9/cairo
copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.9/cairo
copying cairo/py.typed -> build/lib.linux-x86_64-3.9/cairo
running build_ext
building 'cairo._cairo' extension
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/cairo
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=21 -DPYCAIRO_VERSION_MICRO=0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/home/tubbadu/virtualenv/include -I/usr/include/python3.9 -c cairo/bufferproxy.c -o build/temp.linux-x86_64-3.9/cairo/bufferproxy.o -Wall -Warray-bounds -Wcast-align -Wconversion -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-security -Wimplicit-function-declaration -Winit-self -Winline -Wmissing-format-attribute -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wreturn-type-Wshadow -Wsign-compare -Wstrict-aliasing -Wundef -Wunused-but-set-variable -Wswitch-default -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-command-line-argument -fno-strict-aliasing -fvisibility=hidden -std=c99
cairo/bufferproxy.c:32:10: fatal error: Python.h: File o directory non esistente
32 | #include <Python.h>
|          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip wasunable to connect to the PyPI server.
```

**To Reproduce**
I just followed the tutorial on the docs, installed dependencies, created the virtualenv, installed briefcase, run `briefcase new`, let the default value to everything, then `cd helloworld` and `briefcase dev`

**Expected behavior**
application run normally

**Environment:**
 - Operating System: Kubuntu 22.04
 - Python version: 3.9.10
 - pip version: 22.0.4
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: don't know how to get

**Comment by freakboy3742** [comment] 2022-03-22 22:50
This looks like you're missing some of the dependencies of Toga - in this case, I suspect `python-dev` is the root cause of this specific error, but you'll get similar errors if you don't install all the required libs. If you're following the BeeWare tutorial, the step you've missed is [this one](https://github.com/beeware/toga); the Toga tutorial has a similar step, and the same step is mentioned in the Toga README. 

Closing on the basis that it appears to be an error of usage. If you believe you've followed all the dependency steps correctly, let us know and we can re-open.

**Closed by freakboy3742** 2022-03-22 22:50 UTC
Labels: invalid

**Comment by tubbadu** [comment] 2022-03-23 14:38
> This looks like you're missing some of the dependencies of Toga - in this case, I suspect `python-dev` is the root cause of this specific error, but you'll get similar errors if you don't install all the required libs. If you're following the BeeWare tutorial, the step you've missed is [this one](https://github.com/beeware/toga); the Toga tutorial has a similar step, and the same step is mentioned in the Toga README.
> 
> Closing on the basis that it appears to be an error of usage. If you believe you've followed all the dependency steps correctly, let us know and we can re-open.

thanks for answering! 
anyway, both `python-dev-is-python2` and `python3-dev` were already installed at the latest version (3.10.1 for python3-dev... perhaps should it be downgraded to the version 3.9 like the python3 interpreter? I had to switch from python3.10 to 3.9 because toga didn't work with 3.10, then after a few time (and a long update), this error came out, even when running in a virtualenv)
retried running `sudo apt-get install python3-dev python3-gi python3-gi-cairo libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0` but all packages were up to date
thanks for your time!

**Comment by freakboy3742** [comment] 2022-03-25 04:20
Ok - we've reached the point where I can't provide much more assistance - it's down to you to work out what is going on with your Linux install.

The command that is failing is `pip install pycairo` - this command needs to succeed in your virtual environment. The error that is being reported suggests that Python.h isn't available, this is usually provided by python3-dev, but:

1. You're using Kubuntu, not Ubuntu, so I don't know if that changes anything
2. You're using Kubuntu 22.04; I've only tested with Ubuntu 20.04.
3. You've mentioned having multiple python3 installs, and possibly having python2 as well (based on `python-dev-is-python2`)

If you've got multiple Python interpreters installed, that's likely the underlying cause of the problem - especially if you've using something other than the system-provide Python. You need to have the development libraries *for the Python you're actually using*, and they need to be in your environment using the appropriate LD_FLAGS and include paths. If you're *just* using the system-provided Python3, this usually works; but the further you stray off the path, the more you need to do manually. 

Unfortunately, I can't provide much more assistance than this; due to the way Linux is packaged, it's almost impossible to provide instructions that work for all users. It's an unfortunate fact that the Linux ecosystem relies on the fact that that the user understands how their particular machine has been configured.

**Comment by tubbadu** [comment] 2022-03-25 07:33
Okay, I'll try to figure it out! Thanks for your time!
