### ISSUE TITLE
Python 3.9 Support

### ISSUE THREAD

**Issue by h4nsr0b** [beeware/briefcase#540] opened 2020-12-09 00:39 UTC
Newbie here!

I have been following the tutorial to create my very first Beeware app, but on step 3 (Packaging for Distribution), I get:

    (beeware-venv) myapp:briefcase create

    [myapp] Generating application template...
    Using app template: https://github.com/beeware/briefcase-macOS-app-template.git
    Template does not support 3.9

Python's install on my machine:
   
    Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
    [Clang 6.0 (clang-600.0.57)] on darwin

**Comment by freakboy3742** [comment] 2020-12-09 07:45
Thanks for the report. Adding support for new Python versions is something that requires additional testing (and sometimes porting, especially on iOS); it's on our radar to address.

**Comment by synergit** [comment] 2020-12-21 03:22
If you are a Newbie to Python version, please check this [stackoverflow question](https://stackoverflow.com/questions/62898911/how-to-downgrade-python-version-from-3-8-to-3-7-mac) about how to set up specific Python version you need.

**Comment by FriendFromCharlotte** [comment] 2020-12-28 19:28
Also newbie here.  I got to the same point 20 days later.  Is this a problem with 3.9 or with the tutorial?  i.e. are we supposed to downgrade to 3.7 or does 3.9 generally work even though there is an issue with the tutorial?

**Comment by freakboy3742** [comment] 2020-12-30 00:10
@FriendFromCharlotte The issue is that supporting each Python version requires us to build and publish a support package and template for that Python version, and we haven't had time to do this for Python 3.9. I'm not aware of anything that will be fundamentally *broken* with Python 3.9; it's purely a matter of project housekeeping at our end. Addressing this is on my todo list - I might even get to it before the end of the year. 

In the meantime, Python 3.6, 3.7 and 3.8 all work (to the best of my knowledge).

**Comment by pashkatrick** [comment] 2021-01-15 12:37
sorry, but any updates of this issue?

**Comment by freakboy3742** [comment] 2021-01-16 01:32
@pashkatrick No update so far. I've taken an initial look; here's where we stand at present:

* macOS: Python 3.9 added support for the new M1 architecture on macOS, and the support for that architecture conflicts significantly with the patches that we've added to support iOS. I need to reconcile that conflict; this is on my todo list.
* iOS: iOS support packages are produced with the same build tooling as macOS, so the same comment applies.
* Android: Android support also depends on a patched version of Python. I haven't looked at these patches yet.
* Linux: Adding Linux support *should* be relatively straightforward; we don't make any modifications to the Linux build, so this *should* be as simple as pushing a version number update in CI configurations and templates. However, this is lower on my list of priorities because adoption of new Python versions on Linux tends to lag other platforms, because users tend to use the version of Python that comes with their OS, and Ubuntu/Fedora/etc haven't published releases that default to Python 3.9 (that I'm aware of).
* Windows: Windows support is dependent on a Python 3.9 release of Python.net. I have no knowledge on when this will become available.

**Comment by freakboy3742** [comment] 2021-02-14 09:33
Good news! As of this afternoon, thanks to sponsorship from [Butterfly Network](https://butterflynetwork.com), we now have support for Python 3.9 on macOS, iOS, Android, and Linux. The macOS support is still Intel-only for now; thanks to sponsorship from @SamuelJohn from [Otojig](https://otojig.com), we have purchased an M1 Mac Mini, and we're investigating what needs to be done to add support for that new architecture.

Support on Windows is outside our control; it's entirely dependent on the release schedule for Pythonnet.

On that basis, I'm closing this ticket. For updates on M1 Apple Silicon support, follow beeware/Python-Apple-Support#107.

**Closed by freakboy3742** 2021-02-14 09:33 UTC
Labels: android, enhancement, iOS, macOS
