### ISSUE TITLE
MacOS App Cannot Determine Filesystem Encoding

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#869] opened 2022-09-26 22:18 UTC
**Describe the bug**
Running a macOS app fails with error due to unable to get python codec for filesystem encoding.

Error text: `Unable to initialize Python interpreter: failed to get the Python codec of the filesystem encoding`

Note: macOS xcode apps do not throw this error.

**To Reproduce**
Run `briefcase run macos app`.

**Expected behavior**
App should run.

I'm not sure of the root cause but my guess is beeware/Python-Apple-support#161 is related.

It's also possible more work is pending but wanted to report given the upcoming release soon.

**Screenshots**
![image](https://user-images.githubusercontent.com/387848/192389340-e37a56ab-23d7-4123-a0a5-244624c99d4d.png)

**Environment:**
 - Operating System: macOS Monterey 12.6 via VirtualBox on Windows 10
 - Python version: 3.9.11
 - Software versions: 
   - Briefcase: 76490007552dfa13dde8d408b9c40ac76fef4447 (`briefcase -V` reports `0.3.7.dev636+g76490007`)

**Additional context**
[briefcase.2022_09_26-18_08_59.run.log](https://github.com/beeware/briefcase/files/9649960/briefcase.2022_09_26-18_08_59.run.log)

**Comment by freakboy3742** [comment] 2022-09-26 22:52
I can explain this one - you've been bitten by a transitional problem caused by the work on dynamic binary modules. The templates using the new support package layout have been pushed, but the binaries in the app template haven't been updated. Now that #862 has been merged, I can tag and release new binaries; this should be resolved in the next couple of hours.

**Comment by freakboy3742** [comment] 2022-09-27 01:08
This should now be fixed; I've [tagged and built the `dev-b1` binaries](https://github.com/beeware/briefcase-macOS-app-template/actions/runs/3132190795).

**Closed by freakboy3742** 2022-09-27 01:08 UTC
Labels: bug, macOS
