### ISSUE TITLE
[pyproject.toml] Can't let tool.briefcase.version = "{project.version}"

### ISSUE THREAD

**Issue by Pairman** [beeware/briefcase#1675] opened 2024-02-29 17:01 UTC
### Describe the bug

Hello. I'm making my project also a python module to let users use its core services in cli.

I added ```[project]``` and ```[tool.setuptools.packages.find]``` in pyproject.toml to achieve this, and made ```[tool.briefcase]``` and ```[tool.briefcase.app.xdcheckin]``` reference the corresponding terms under ```[project]```, to avoid multiple definitions.

This works great for installing my project as a module and importing its packages. However, it conflicts with briefcase:
```
$ briefcase package -v
Briefcase configuration error: Version number ({project.version}) is not valid.

Version numbers must be PEP440 compliant; see https://www.python.org/dev/peps/pep-0440/ for details.
```

[This is my pyproject.toml. ](https://github.com/Pairman/Xdcheckin/blob/main/pyproject.toml) Is there any way to fix/bypass this? Or will briefcase support this feature? Thanks in advance.

### Steps to reproduce

1. In pyproject.toml, create ```[project]``` and define the version number here.
2. Make ```tool.briefcase.version``` reference ```project.version``` via
```
[tool.briefcase]
version = "{project.version}"
```
3. Run ```briefcase package``` and it will fail.

### Expected behavior

Briefcase parses pyproject.toml and packages successfully.

### Environment

- Operating System: Ubuntu 22.04
- Python version: 3.10
- Software versions:
  - Briefcase: 0.3.16

**Comment by rmartin16** [comment] 2024-02-29 19:43
crosslinking:
- https://github.com/beeware/briefcase/issues/474

**Comment by freakboy3742** [comment] 2024-02-29 22:23
I'm going to close this on the basis that there is no documentation or convention that I'm aware of that would suggest that `"{project.version}"` is valid syntax. 

If the issue is that you want to use PEP621 syntax to define project metadata and not repeat those values in the `tool.briefcase` section, you can do so; the `tool.briefcase` block will inherit [many PEP621 values that have an interpretation](https://briefcase.readthedocs.io/en/stable/reference/configuration.html#pep621-compatibility).

**Closed by freakboy3742** 2024-02-29 22:23 UTC
Labels: bug

**Comment by Pairman** [comment] 2024-02-29 23:35
> I'm going to close this on the basis that there is no documentation or convention that I'm aware of that would suggest that `"{project.version}"` is valid syntax.
> 
> If the issue is that you want to use PEP621 syntax to define project metadata and not repeat those values in the `tool.briefcase` section, you can do so; the `tool.briefcase` block will inherit [many PEP621 values that have an interpretation](https://briefcase.readthedocs.io/en/stable/reference/configuration.html#pep621-compatibility).

Thank you!
