### ISSUE TITLE
[MacOS  =>  iOS ]  briefcase run iOS -u -d "iPad Pro (9.7-inch)::iOS 12.1"   ** BUILD FAILED **

### ISSUE THREAD

**Issue by clemsam** [beeware/briefcase#658] opened 2022-01-23 18:31 UTC
**Describe the bug**
briefcase / toga project build/starts fine as "briefcase dev" (on an Apple Airbook) but does NOT build as "briefcase run iOS"
**To Reproduce**
1. briefcase new (etc. like suggested > "Hello World")
2. briefcase create iOS
3. briefcase run iOS
4. See error:
```
myMac:helloworld me_user$ briefcase run iOS -u -d "iPad Pro (9.7-inch)::iOS 12.1" 
[helloworld] Building XCode project...
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _seq2set in libPython.a(selectmodule.o)
      _set2list in libPython.a(selectmodule.o)
  "_pwritev", referenced from:
      _os_pwritev in libPython.a(posixmodule.o)
  "_preadv", referenced from:
      _os_preadv in libPython.a(posixmodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Using build description from disk
** BUILD FAILED **
```
**Expected behavior**
Obviously the app should be installed to the simulator
**Screenshots**
(Just error text above.)
**Environment:**
 - Operating System: **MacOS 10.13.6 High Sierra**
 - Python version: 3.7
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev20
   - **Xcode 10.1** (iPad simulator running fine from within)

**Additional context**
I'm no IT professional, but searched this github: no results found.
Would also appreciate any "workaround" or NOT merged solution !!! (I used such in [Discussion #1372](https://github.com/beeware/toga/discussions/1372)  _[android] ImageView, NOT merged: How to staple & click them (MahJong solitaire)_

**Comment by freakboy3742** [comment] 2022-01-23 23:59
This is caused by the *very* old version of Xcode and macOS. Xcode doesn't maintain backwards compatibility for more than a year or so; they very much assume that as a developer, you'll keep up to date with macOS and Xcode. You can use that new version of Xcode to build an app that is compatible with older versions of macOS - but as the developer, you need to stay up to date.

To the best of my knowledge, there's no fix for this other than "update your old OS and Xcode".

**Closed by freakboy3742** 2022-01-23 23:59 UTC
Labels: bug

**Comment by clemsam** [comment] 2022-02-09 08:44
Okay. I tried to at least update to 10.14 Mojave which more or less "bricked" my rather old Macbook due to some incompatibility (wifi card or whatever:  Mojave is the LAST OS version running on intel Macs…).
I tried for another ≈10 days to somehow get Mojave installed, with NO success.
I could not even do a fresh re-install of High Sierra – but learned in the process that my (previously updated) Carbon Copy Cloner backup image restored ev.th. in no time.

So, my only hope (as I don't have money for an M1 PB right now…) is to find a pre-installed CCC image (or readily installed SSD) with Mojave on it.
If anybody knows of a CCC download (NOT: a bootable USB install !) please let me know, so I can then install Xcode 10.3 in a regular way and take my MahJong project to the Xcode simulator, at least.
Thanx for any idea | hint!    clemsam
