### ISSUE TITLE
Adding binary files to the application

### ISSUE THREAD

**Issue by pwildenhain** [beeware/briefcase#773] opened 2022-06-27 13:41 UTC
On windows, in order to use the `pyodbc` library, you need Visual Studio C++ Build tools installed. Would it be possible to pre-package this in my briefcase app? Or would I need to ensure the users have it installed on their machine before running the application?

If the users must have it on their machine, it there a way for me to warn them that they don't have it installed when they go to run the app?

I'm very new to the world of desktop app development, so this might be off, but I believe `pyinstaller` provides this sort of functionality: https://pyinstaller.org/en/stable/spec-files.html#adding-binary-files

**Comment by freakboy3742** [comment] 2022-06-28 01:08
This is effectively a duplicate of #485. At present, we don't have a solution for this. The best option I can offer at present is to catch any error raised by PyODBC when it is imported and the dependencies aren't present, or speculatively probe for those dependencies at startup. Toga contains examples of this beheavior in the [winforms](https://github.com/beeware/toga/blob/main/src/winforms/toga_winforms/widgets/webview.py#L76) and [gtk](https://github.com/beeware/toga/blob/main/src/gtk/toga_gtk/widgets/webview.py#L13) Webview implementations.

**Closed by freakboy3742** 2022-06-28 01:08 UTC
Labels: duplicate, question

**Comment by pwildenhain** [comment] 2022-06-28 01:26
Darn, I promised I scoured far and wide for someone who had asked a question like this before, including last issues.

Thanks for the prompt reply. In my case it's not a deal breaker to ensure that the host system has the proper software installed
