### ISSUE TITLE
Tutorial 1 - ImportError: No module named 'toga.django'

### ISSUE THREAD

**Issue by Fedorof** [beeware/briefcase#115] opened 2018-04-06 20:04 UTC
The app for Django is successfully build, but any manage.py command fails with error "ImportError: No module named 'toga.django'"

Downgrading to 0.2.15 version of toga-django plus using the old version of the tutorial  fixes the issue.

OS version: Ubuntu 14.04
Python 3.5.5

```
$ pip freeze

arrow==0.12.1
binaryornot==0.4.4
boto3==1.7.2
botocore==1.10.2
briefcase==0.2.1
certifi==2018.1.18
chardet==3.0.4
click==6.7
cookiecutter==1.6.0
Django==1.10.6
django-environ==0.4.1
docutils==0.14
future==0.16.0
idna==2.6
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
MarkupSafe==1.0
poyo==0.4.1
python-dateutil==2.6.1
requests==2.18.4
s3transfer==0.1.13
six==1.11.0
toga-core==0.3.0.dev8
toga-django==0.3.0.dev8
travertino==0.1.2
urllib3==1.22
voc==0.1.5
whichcraft==0.4.1
```

```
$ ./manage.py

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cabox/workspace/pybee/tutorial/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/cabox/workspace/pybee/tutorial/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/cabox/workspace/pybee/tutorial/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cabox/workspace/pybee/tutorial/venv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/cabox/workspace/pybee/tutorial/venv/lib/python3.5/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/cabox/.pyenv/versions/3.5.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'toga.django'
```

**Comment by freakboy3742** [comment] 2018-04-06 22:53
Thanks for the report; this is a known problem, largely caused by the fact that the 0.3.0 branch is in a development state.

**Comment by Fedorof** [comment] 2018-04-07 06:48
Thank you for the answer. Is it correct that the fix is to implement the issue [#73](https://github.com/pybee/briefcase/issues/73)?

**Comment by freakboy3742** [comment] 2018-04-07 07:46
@Fedorof No - it's not a problem with briefcase. The issue is that the 0.3.0 release involves a big code restructure, and we haven't updated the code for the Django backend to reflect the new code structure.

**Comment by emmagordon** [comment] 2018-05-26 10:30
@Fedorof - re the workaround - "Downgrading to 0.2.15 version of toga-django plus using the old version of the tutorial fixes the issue"  - could you post a link to the version of the tutorial you used please? Only doing the downgrade just causes a different error.

**Comment by freakboy3742** [comment] 2018-05-26 10:51
@emmagordon Read The Docs has a version switcher on the bottom left ion the screen; you can use that to get to the [0.2.15 version of the tutorial](https://toga.readthedocs.io/en/v0.2.15/tutorial/index.html#tutorial)

**Comment by emmagordon** [comment] 2018-05-26 13:32
@freakboy3742 - thanks. However, although the toga tutorial has various versions listed, the only options for the briefcase tutorial are latest/stable, with both ending up with this issue. Perhaps for the stable briefcase tutorial docs, it should use something other than "cookiecutter https://github.com/pybee/briefcase-template" which will grab the latest development version?

**Comment by bobm123** [comment] 2018-06-30 15:45
I'd like to try my hand at fixing this issue but I'm not sure where to start. I'm planning to do a lunch-n-learn presentation at work and would like so show an example of a Toga app running in the browser, but this is a blocker. I am seeing the "No module named 'toga.django'" error that @emmagordon reported. I also noticed the build scripts re-install 'Django 1.10.6' and several other modules. Could this be related?

**Comment by Aventine1** [comment] 2019-01-11 18:15
I also encountered this issue while doing https://briefcase.readthedocs.io/en/latest/tutorial/tutorial-1.html#
when running
``python setup.py django -s``
After reading the issues here on github, I recreated my venv and did 
``pip install --pre toga-django``
to obtain
``arrow==0.13.0
binaryornot==0.4.4
boto3==1.9.77
botocore==1.12.77
briefcase==0.2.8
certifi==2018.11.29
chardet==3.0.4
Click==7.0
cookiecutter==1.6.0
Django==1.10.6
django-environ==0.4.1
docutils==0.14
future==0.17.1
idna==2.8
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
MarkupSafe==1.1.0
pkg-resources==0.0.0
poyo==0.4.2
pycairo==1.18.0
python-dateutil==2.7.5
requests==2.21.0
s3transfer==0.1.13
six==1.12.0
toga-core==0.3.0.dev11
toga-django==0.3.0.dev11
travertino==0.1.2
urllib3==1.23
voc==0.1.6
whichcraft==0.5.2
``
and still encountered the issue.
I was unable to find a way to get it to work.

If current and previous versions of the Briefcase tutorial's Django section are non-functional, they should be characterized as such in the docs.  The tutorial gives the impression that it should just work, but from here it seems they don't work in any version or environment.  I mean just the Django section of Briefcase tutorial linked above.

**Comment by freakboy3742** [comment] 2019-12-21 00:59
We've temporarily disabled our Django backend due to the limitations in using the 0.3 branch of Toga. Closing this ticket until we're able to re-add web support.

**Closed by freakboy3742** 2019-12-21 00:59 UTC
