### ISSUE TITLE
android beeware problem

### ISSUE THREAD

**Issue by Pipsy100** [beeware/briefcase#178] opened 2018-11-11 12:35 UTC
Hello, I am new to Beeware and I know a bit about Android.
When I try to compile I get this message

anybody any idea what the problem might be?

Thx in adv. Willem

> Task :transformClassesWithDexBuilderForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\_Projects\Python\Beeware\tutorial\venv\helloworld\android\libs\python-android-support.jar

**Comment by Pipsy100** [comment] 2018-11-11 13:04
This seems to be the problem according to the stacktrace

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead

**Comment by freakboy3742** [comment] 2018-11-11 22:17
@Pipsy100 Thanks for the report - however, while your diagnosis is a problem that needs to be addressed, it's not the source of the bug you've reported. 

We use a tool called VOC to compile Python code into Java bytecode; however, VOC is currently producing invalid bytecode for Toga apps. This is for two reasons:

* A recent change in VOC has introduced a bug when compiling classes. The bytecode that is being generated is valid for all our test cases, but for some reason, it's raising an error when it's compiled to DEX, the internal format Android uses.
* Toga hasn't been updated to make sure it works on Android.

The second point has been caused by the first - we can't update Toga until the VOC bug is resolved, because we can't verify any fix.

There is also a need to update the gradle file to avoid the warning that you've reported here - however, I haven't found a good explanation of what that warning actually *means* in practical terms.

**Comment by Tadaboody** [comment] 2018-11-21 14:09
Why not freeze the VOC and Toga version to those that work? at least until the bugs are resolved

**Comment by freakboy3742** [comment] 2018-11-22 00:38
@Tadaboody We *have* done that - at least, to the extent that is possible. The current "stable" version of Toga (0.2.15) can be made to work on Android - but that version doesn't work on macOS High Sierra, because there have been changes made to macOS that have been fixed in the 0.3 "unstable" development branch. 

The problem is that we haven't got a single "stable" version. There are lots of moving parts that all need to be kept in sync. And the underlying platforms are changing at the same time. 

Fundamentally, what is needed is more developer attention. This is a project that I only get to work on in my spare time. As a result, platforms that I don't *personally* use that often (Windows, Android) lag behind in support. 

I know it's hard for people to get involved when something doesn't work out of the box. 18 months ago, Android support *did* work out of the box. But it's incredibly difficult to (a) keep everything working, (b) on 6 platforms simultaneously, while (c) adding new features, and (d) doing it all, largely by myself, in my spare time.

**Comment by paapu88** [comment] 2019-03-10 18:58
Getting the same error, any workaround? Can one use beeware for android at all ? 
If not please remove instructions for android so that people are not wasting their time.
I'm on xubuntu 18.04
Terveisin, Markus
´´´
* What went wrong:
Execution failed for task ':transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/mka/Briefcase/tutorial/helloworld/android/libs/python-android-support.jar
´´´

**Comment by finedust** [comment] 2019-04-26 11:46
I have the same problem without even using Toga in the app actually.

**Comment by freakboy3742** [comment] 2019-04-27 02:38
@finedust Yes - the error indicates a problem compilng .class files to Android's DEX format; if there's a problem with the .class file, then the DEX compilation will fail. The Python standard library that currently ships with Python-Android-support has some modules that don't successfully compile with DEX.

**Comment by rixx** [comment] 2019-04-27 20:11
Is there any point where we can start hacking around this issue? I'd be willing to dig into that if you can shove me in the right starting direction.

**Comment by freakboy3742** [comment] 2019-04-28 00:35
@rixx Broadly, there are two possible ways to approaching this:

1. Fix VOC's compilation so it is DEX compatible.
2. Change the approach used on Android to be based on embedding CPython.

(1) is the "fix what's there" approach; it mostly requires Python and Java skills. (2) is an entirely different approach, requiring Python and C skills (and a little Java, but mostly in a JNI context).

If you want to try your hand at (1): There's a fix for the deprecation error in the gradle configuration contained in beeware/Python-Android-template#25; beyond that, the approach is to run Android's dex tool on individual class files (for example, the class files in python-android-support.jar), find one example of a specific class that fails, work out what about the generated class file is causing a problem, then fix VOC so it doesn't output invalid class files. Ideally, that would also involve introducing a unit test into the VOC build process so that we can't produce a support library that won't DEX.

The problem will almost always be in the way the stack size is allocated in stack frames. The JVM requires each function to define how large the stack will be; you can produce a class file that meets the binary requirement, but will fail at runtime because it doesn't have sufficient stack allocated for a method. 

Actually diagnosing why the stack size is wrong is a harder problem - the tooling around diagnosing problems with class files is weak, because most people don't have this problem :-) However, my experience has been that if DEXing fails, actually running the java code will also fail; so it becomes a matter of searching for the specific piece of Python code that has been compiled that is causing the problem.

That said - I've been increasingly coming to the opinion that (1) will take a lot of effort to produce a workable solution. Getting all the C portions of CPython ported to Java will take a while; and there are lots of projects with C modules that will also need to be ported (e.g., requests uses cryptography, which has a C module; so you won't be able to use all of requests on Android without porting that portion to Java. That's *doable*; and there might even be a way to compile the C module so it can be used by the Python code - but it's going to be a big job, either way.

That leaves (2). I had this working a long time ago, but abandoned the approach because JNI on Android was slow. However, in the intervening years, phone CPUs have become as fast as laptops, so I figured it was worth another look. I have some initial code for this approach; I've got CPython compiled for Android, and I've got that integrated into an Android project, but it's currently segfaulting when the Python VM starts. I'm trying to work out why; if you're interested in digging in here, let me know and I can share the code as it stands.

**Comment by freakboy3742** [comment] 2019-12-21 01:03
We've formally marked our Android backend as broken; this should hopefully be addressed in the near future thanks to a grant from the Python Software Foundation Education Grants committee. In the meantime, there's no point maintaining an open ticket, Android is effectively (for now) an unsupported platform.

**Closed by freakboy3742** 2019-12-21 01:03 UTC
