### ISSUE TITLE
runtime issues

### ISSUE THREAD

**Issue by Sergeam22** [beeware/briefcase#850] opened 2022-09-03 19:19 UTC
The location Briefcase will use to store tools and support files:

    C:\Users\SERGE AMINI\AppData\Local\BeeWare\briefcase\Cache

contains spaces. This will cause problems with some tools, preventing
you from building and packaging applications.

You can set the environment variable BRIEFCASE_HOME to specify
a custom location for Briefcase's tools.

**Comment by freakboy3742** [comment] 2022-09-04 23:05
Thanks; since you're have posted Briefcase's own error message, which contains the explanation and solution of the problem, I'm going to close this as already fixed.

Fundamentally - the issue here is that you have a space in your username, which is generally speaking, a bad idea. 

Yes, it's a cause of problems. However, the cause of the failure is completely outside our control - some tools (most notably, the Android toolchain, but there are others) - don't work if you have a space in the path where the tools are installed; and we provide a warning if this condition is detected.

The platform appropriate path to install tools is in your user folder. I can't think of any other location that is available and appropriate for user-space installations. If you have a space in your username, this means the path isn't safe for all tools.

A workaround exists, and is described in the error message you've received: define a `BRIEFCASE_HOME` environment variable. Or, the better fix - rename your user account - because Briefcase isn't the only tool that will have a problem with spaces in your user name.

**Closed by freakboy3742** 2022-09-04 23:05 UTC
Labels: invalid

**Comment by mhsmith** [comment] 2022-09-05 07:30
> A workaround exists, and is described in the error message you've received: define a `BRIEFCASE_HOME` environment variable.

Specifically:
* Create a new folder outside of your user folder, e.g. C:\BriefcaseHome
* Go to the environment variable settings. On Windows 10, you can find them by opening the start menu and typing "environment".
* Add a new variable:
  * Name: `BRIEFCASE_HOME`
  * Value: the folder you created above.
* Exit and restart the terminal you were using to run Briefcase.
