### ISSUE TITLE
permission error with `python setup.py ios`

### ISSUE THREAD

**Issue by BrendanSimon** [beeware/briefcase#181] opened 2018-12-02 12:23 UTC
I've created a simple toga app (some tabs using OptionContainer and each tab containing a Table).

It builds and runs ok on macos with `python setup.py macos`, however it fails when building for iOS.

BTW, I'm running everything within a `pipenv` environment (my first play with it), python3.6, toga 0.3.0dev11 (installed with `pipenv install --pre toga toga-ios`)

Xcode does seem to build it ok (with a couple of warnings), but the app does not run in the sim.  I just get a dark screen.

Any idea how to resolve this?

> $ python setup.py ios
> running ios
>  * Writing application template...
> Template Python-iOS-template succesfully updated.
> Project template: /Users/brendan/.cookiecutters/Python-iOS-template
>  * Determining best support package...
>  * Installing support package...
> Support package: https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Apple-support/3.6/iOS/Python-3.6-iOS-support.b7.tar.gz
> Already downloaded
>  * Installing requirements...
> Collecting toga==0.3.0.dev11
>   Using cached https://files.pythonhosted.org/packages/04/73/3ded37ce19d9657be425fffd1ee76d7cde26395baab17c01548db0230927/toga-0.3.0.dev11-py3-none-any.whl
> Collecting toga-cocoa==0.3.0.dev11; sys_platform == "darwin" (from toga==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/a1/94/51111404743373ad6f201df04ca312d0dbfd833fb656e7e58e07bec2e6a8/toga_cocoa-0.3.0.dev11-py3-none-any.whl
> Collecting toga-core==0.3.0.dev11 (from toga-cocoa==0.3.0.dev11; sys_platform == "darwin"->toga==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
> Collecting rubicon-objc>=0.3.0 (from toga-cocoa==0.3.0.dev11; sys_platform == "darwin"->toga==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/ce/55/b7fbfd72cbd3d18322d94305179c6c1805fe4b5e10619d6954adf7f1d6a3/rubicon_objc-0.3.0-py2.py3-none-any.whl
> Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-cocoa==0.3.0.dev11; sys_platform == "darwin"->toga==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
> Installing collected packages: travertino, toga-core, rubicon-objc, toga-cocoa, toga
> Successfully installed rubicon-objc-0.3.0 toga-0.3.0.dev11 toga-cocoa-0.3.0.dev11 toga-core-0.3.0.dev11 travertino-0.1.2
>  * Installing platform requirements...
> Collecting toga-ios==0.3.0.dev11
>   Using cached https://files.pythonhosted.org/packages/36/f1/a5e2f2390b3129768e2399d6c8a2e5ef3ffb2bf82f4e5e33b6bf7842dc7d/toga_iOS-0.3.0.dev11-py3-none-any.whl
> Collecting toga-core==0.3.0.dev11 (from toga-ios==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
> Collecting rubicon-objc>=0.3.0 (from toga-ios==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/ce/55/b7fbfd72cbd3d18322d94305179c6c1805fe4b5e10619d6954adf7f1d6a3/rubicon_objc-0.3.0-py2.py3-none-any.whl
> Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-ios==0.3.0.dev11)
>   Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
> Installing collected packages: travertino, toga-core, rubicon-objc, toga-ios
> Successfully installed rubicon-objc-0.3.0 toga-core-0.3.0.dev11 toga-ios-0.3.0.dev11 travertino-0.1.2
>  * Installing project code...
> Processing /Users/brendan/Sandbox/sggc_live
> Building wheels for collected packages: sggc-live
>   Running setup.py bdist_wheel for sggc-live ... done
>   Stored in directory: /private/var/folders/1h/df5214x933ndx_mpl0h71l_r0000gn/T/pip-ephem-wheel-cache-gw6ye3uz/wheels/a4/2c/8d/d6d9a41aed61ed154a4e383dc33604a3522ae166552a3c37c8
> Successfully built sggc-live
> Installing collected packages: sggc-live
> Successfully installed sggc-live-0.3.0.dev11
>  * Creating launchers...
> Collecting setuptools
>   Using cached https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl
> Installing collected packages: setuptools
> Successfully installed setuptools-40.6.2
> Installing sggc_live script to /Users/brendan/Sandbox/sggc_live/iOS/app
> error: [Errno 1] Operation not permitted: '/Users/brendan/Sandbox/sggc_live/iOS/app/sggc_live'

**Comment by BrendanSimon** [comment] 2019-01-01 23:31
Bump!  Any solution/updates/hints/tips/suggestions on this error?

**Comment by freakboy3742** [comment] 2019-01-02 03:01
A little more digging revealed that the problem is that `launcher_script_location` defaults to the app directory; but when that is combined with the resource directory on line 365 of app.py to produce `rel_sesources` (which should be `rel_resources`...), you get `..` - which won't be a valid output directory.

**Comment by BrendanSimon** [comment] 2019-01-02 03:09
All sounds very promising, with a potential fix/workaround not too far away :)
Will there be another release of briefcase soon, or am I best to clone the repo and work with the dev code?

What to do re OptionContainer or Table widget not being implemented on iOS?  Should separate issues be opened somewhere else (toga)?  Is this stuff easy to implement?  I tend to use those type of widgets often in other GUI frameworks (e.g. notebooks and grid in wxPython)

**Comment by freakboy3742** [comment] 2019-12-21 01:17
The briefcase 0.3 development branch moves away from setup.py as a configuration format, and as a result, the problems around entrypoints should no longer exist. 

Widget support is an ongoing problem; however, it's a Toga issue, not a briefcase problem.

Closing this ticket on the basis that there's nothing specifically left that is a bug in briefcase. If you encounter similar problems in the current development branch (using the new configuration format) please open a new ticket.

**Closed by freakboy3742** 2019-12-21 01:17 UTC

**Comment by BrendanSimon** [comment] 2019-12-21 10:49
Ok.  How do you run things now (instead of setup.py?).  Is there any documentation?  The current docs still reference `python setup.py <target> -s`

https://briefcase.readthedocs.io/en/latest/

**Comment by freakboy3742** [comment] 2019-12-21 10:56
My apologies - looks like a configuration error on Read The Docs prevented the new docs from being built. I've corrected the problem; the new docs are live.

The docs are still a work in progress; however, the tutorial linked from the briefcase tutorial page should give you enough detail to get going.

**Comment by BrendanSimon** [comment] 2019-12-21 11:33
Following the latest docs for Tutorial 0 gives an error when running `python setup.py ... -s`

NOTE: dev environment is in a fresh `venv`, with `pip install --pre` for `cookiecutter`, `briefcase`, `toga-cocoa`

```
$ python setup.py macos -s
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'macos'
```

**Comment by freakboy3742** [comment] 2019-12-21 11:56
I think you might be looking at a stale cache page for the tutorial - there shouldn't be a tutorial-0 for briefcase any more. The current page footer should reference revision `eacffc0b`, and redirect you to https://beeware.readthedocs.org

**Comment by BrendanSimon** [comment] 2019-12-21 12:07
Ok.  Got it.  Thanks :)

**Comment by BrendanSimon** [comment] 2019-12-21 12:27
Just a quick note that the "Say Hello!" button is not working in the iOS simulator.

I can enter test in the text box, but the "Say Hello!" button looks and feels like static text, rather than a button.  Nothing happens when I click on it.  I tried with "iPhone 8" and "iPhone 11" builds and sims.

Do you want a new issue for this?

**Comment by freakboy3742** [comment] 2019-12-21 12:30
The look of the button is (unfortunately) the default behavior of iOS. The "flat" style of iOS apps means that buttons look like text now. Personally, I hate the "flat design" trend - but that is what the platform style guide says, so that's what Toga does.

I was aware of the problem with the dialog not appearing - it was on my list of things to look at tomorrow. However, if you wanted to open a ticket in the meantime, it might help anyone else who hits the same problem.
