### ISSUE TITLE
Dist-info from previous versions is kept in the app path

### ISSUE THREAD

**Issue by samschott** [beeware/briefcase#720] opened 2022-04-22 18:50 UTC
**Describe the bug**
When running `briefcase update`, `CreateCommand.install_app_code()` will replace any old app code with the new version and write up-to-date dist-info to the app path. It will however not clear stale dist-info from previous versions.

A similar problem with dist-info for app packages was fixed in #645.

**To Reproduce**
Update the app code with `briefcase update` after incrementing the project version.

**Expected behavior**
Remove old dist-info.

**Environment:**
 - Software versions:
   - Briefcase: 0.3.6

**Additional context**

**Comment by freakboy3742** [comment] 2022-04-23 00:11
This is a borderline duplicate of #472. The underlying problem is that the app is only rolled out on `create`; as a result, any details in the generated content that come from pyproject.toml won't be updated. 

In the case of #472, the issue is caused because the WIX config file that is generated comes from the app template. In this case, the dist-info folder is generated by Briefcase. That means it should be relatively straightforward to fix *this* manifestation of the problem; #472 will be a bit harder, because it involves overwriting *some* of the project template.

As an immediate workaround, users can avoid `update`, and re-create the app every time they update major app details. That's not ideal as a long term solution, but it will *work*.

**Comment by samschott** [comment] 2022-04-23 09:38
Yes, this is indeed very similar to #472, maybe actually a duplicate. 

The fix proposed in #721 is cross platform in the sense that it indeed removes all stale files in the app path. I’m not sure however if this is already sufficient. I’ll need to have a look at which info in the WiX template becomes stale when bumping the app version, from skimming the discussion it appears that the situation may be more complex.

**Comment by samschott** [comment] 2022-04-23 11:34
Ok, I understand what you mean now. Clearly, the changes in PR #721 won't fix #472, there is other metadata which needs to be updated when fields in the pyproject.toml change. I am currently taking care of some of this by "manually" bumping the app version with bump2version instead of briefcase.

**Closed** 2022-04-24 00:59 UTC
Labels: bug, up-for-grabs
