### ISSUE TITLE
0.2.10 adds an unneeded requirement for a full xcode for macos

### ISSUE THREAD

**Issue by nolanl** [beeware/briefcase#295] opened 2020-01-07 20:28 UTC
9c1f0ae0fe429c35cff1eefa045a18b50a3e48f3 adds a check for both Xcode and the Command Line Tools to macos.py.

This broke my CI when I upgraded from 0.2.9 to 0.2.10. Simply installing Xcode is not ideal because it is a) huge, and b) requires a GUI to install, which my CI VM doesn't have.

As far as I can tell, 0.2.10 didn't add any new code that requires a full Xcode install, so I manually patched out the check (leaving the check for the Command Line Tools) and everything works again.

**Comment by freakboy3742** [comment] 2020-01-08 02:07
@nolanl Thanks for the report; Looks like this is a duplicate of #270. It's been addressed in the development of v0.3.

v0.3 is available as a pre-release (i.e., `pip install --pre briefcase`); however, be advised that there have been some significant changes to the configuration format. There's [a migration guide](https://briefcase.readthedocs.io/en/latest/how-to/upgrade-from-v0.2.html) to assist with the transition.

**Closed by freakboy3742** 2020-01-08 02:07 UTC
Labels: duplicate

**Comment by nolanl** [comment] 2020-01-08 02:25
Thanks for the link to the migration guide.  I was hoping to avoid upgrading to 0.3 until it is released.  For anyone else in my situation, this is the workaround I used in my build script:
```sed -i '' 's/xcodebuild/true/1' /Users/vagrant/venv/lib/python3.7/site-packages/briefcase/macos.py```
