### ISSUE TITLE
Briefcase create : Python 3.10 and/or aarch64 is not yet supported

### ISSUE THREAD

**Issue by GaelJaboulay** [beeware/briefcase#818] opened 2022-08-10 15:21 UTC
Trying to setup briefcase using Raspberry PI 400 with Ubuntu Mate 22.04.1 LTD 64-bits. Linux 5.15.0-1012-raspi aarch64
Mate 1.26.0
Python 3.10.4
All the steps went ok until https://docs.beeware.org/en/latest/tutorial/tutorial-3.html 
When I run the command "briefcase create", I get 404 Not Found 
The link : "https://briefcase-support.org/python?platform=linux&version=3.10&arch=aarch64"
Error message: Python 3.10 and/or aarch64 is not yet supported

Maybe because of aarch64 ? Can you support it?

**Comment by freakboy3742** [comment] 2022-08-10 22:22
Duplicate of #449.

The complication with providing Raspberry Pi support is that Linuxdeploy (which we use to provide AppImage support) doesn't currently publish Raspberry Pi-compatible tools, and they don't appear to have any plans to do so.

I believe Flatpak may be able to support Raspberry Pi, though... if fact, it *might* work out of the box (although no promises on this, as it hasn't been tested). Flatpak support will land in the next release of Briefcase; once it does, `briefcase <cmd> linux flatpak` will generate Flatpak output.

**Closed by freakboy3742** 2022-08-10 22:22 UTC
Labels: duplicate, enhancement
