### ISSUE TITLE
changed installer_icon but it does not work，the `.exe` icon is still the previously set image.

### ISSUE THREAD

**Issue by dreamcatgit** [beeware/briefcase#2076] opened 2024-12-06 04:03 UTC
### Describe the bug

I had previously set the **installer_icon**, and it worked successfully. However, now I want to change to a new **installer_icon**, but it doesn't take effect. Even after changing the name of the **.ico** file, updating the **icon** and **installer_icon** attributes in the **pyproject.toml** file, deleting the build folder, and re-running **briefcase create**, **briefcase build**, or **briefcase build -r**, the **.exe** file icon remains the same as the previous image.

### Steps to reproduce

1. change ico file
2. reset pyproject.toml file  **installer_icon** and **icon**
3. del build folder
4. **briefcase create**
5. **briefcase build -r**
6. check **.exe**

### Expected behavior

changed installer_icon but it does not work，the `.exe` icon is still the previously set image.

### Environment

- Operating System:windows 10
- Python version:3.9.7
- Software versions:
  - Briefcase:0.3.20
  - pyside6:

### Logs

```

```

**Comment by freakboy3742** [comment] 2024-12-06 04:24
Thanks for the report. We've had reports of something similar to this in the past; historically, the issue is that operating systems sometimes cache icons - and even though the source icon changes, the operating system will continue to display the stale one.

Assuming that you're correctly updating the icon (and it sounds like you are - `briefcase create` in particular should be installing any new icon), the usual fix is to reboot. 

I agree that's not a very satisfying answer, but I'm not aware of a way on Windows to programmatically reset the operating system icon cache. 

Can you try rebooting and report if that fixes the problem?

**Comment by dreamcatgit** [comment] 2024-12-06 07:40
@freakboy3742 
Thank you! It worked, but I didn’t reboot the system. Based on your suggestion, I thought of using a PC management tool to clear the system cache. After repackaging, it worked perfectly!

**Comment by freakboy3742** [comment] 2024-12-08 22:55
Glad you were able to resolve this. I'm going to close this ticket; while the issue definitely still exists, it is "working as expected" in the sense that it's working the way that Windows intends and allows.

If anyone is able to find a programmatic way for Briefcase to flush the cache in a way that prevents the issue, we'll gladly entertain a patch.

**Closed by freakboy3742** 2024-12-08 22:55 UTC
Labels: bug, windows
