### ISSUE TITLE
briefcase dev stops working after pip install -e . to overcome the vscode "No Module" problem

### ISSUE THREAD

**Issue by alexrjs** [beeware/briefcase#1391] opened 2023-07-29 20:20 UTC
### Describe the bug

Wanted to debug in vscode, since "breakpoint()" is not fun. Was not working, so I installed module with "pip install -e ." afterwards "briefcase dev" wasn't working anymore. Don't know what is wrong.

output:

> briefcase dev

> [togasample] Starting in dev mode...
===========================================================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/alexrjs/Sources/py/togasample/src/togasample/__main__.py", line 4, in <module>
    main().main_loop()
    ^^^^^^
  File "/Users/alexrjs/Sources/py/togasample/src/togasample/app.py", line 26, in main
    return TogaSample()
           ^^^^^^^^^^^^
  File "/Users/alexrjs/.venv/toga-test/lib/python3.11/site-packages/toga/app.py", line 279, in __init__
    raise RuntimeError("Toga application must have a formal name")
RuntimeError: Toga application must have a formal name

> Problem running app togasample.

> Log saved to /Users/alexrjs/Sources/py/togasample/logs/briefcase.2023_07_29-21_59_21.dev.log

### Steps to reproduce

1. Prepare a new toga project like in the tutorial -> used togasample as name
2. do the cd and briefcase dev -> works
3. Open code with "code ."
4. open the "__main__.py" go to debug tab and use the "Run and Debug" button -> Fails with failed module.
5. Open Terminal ensure the virtualenv from step 1 is active and execute "pip install -e ." where the pyproject.tmol is located
6. run "briefcase dev" -> not working anymore
output:

> briefcase dev

> [togasample] Starting in dev mode...
===========================================================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/alexrjs/Sources/py/togasample/src/togasample/__main__.py", line 4, in <module>
    main().main_loop()
    ^^^^^^
  File "/Users/alexrjs/Sources/py/togasample/src/togasample/app.py", line 26, in main
    return TogaSample()
           ^^^^^^^^^^^^
  File "/Users/alexrjs/.venv/toga-test/lib/python3.11/site-packages/toga/app.py", line 279, in __init__
    raise RuntimeError("Toga application must have a formal name")
RuntimeError: Toga application must have a formal name

> Problem running app togasample.

> Log saved to /Users/alexrjs/Sources/py/togasample/logs/briefcase.2023_07_29-21_59_21.dev.log

 7. pip uninstall togosample
 8. run "briefcase dev" again -> still not working
[briefcase.2023_07_29-21_56_06.dev.log](https://github.com/beeware/briefcase/files/12207905/briefcase.2023_07_29-21_56_06.dev.log)

 

### Expected behavior

1. pip install -e . shouldn't be necessary in vscode to debug
2. if 1. is needed I expect briefcase dev to run normally
3. Bonus: debuging in vscode shouldn't be fail with 
Exception has occurred: ValueError
A distribution name is required.
  File "/Users/alexrjs/Sources/py/togasample/src/togasample/app.py", line 26, in main
    return TogaSample()
           ^^^^^^^^^^^^
  File "/Users/alexrjs/Sources/py/togasample/src/togasample/__main__.py", line 4, in <module>
    main().main_loop()
    ^^^^^^
ValueError: A distribution name is required.

### Screenshots

<img width="1155" alt="Bildschirmfoto 2023-07-29 um 22 13 19" src="https://github.com/beeware/briefcase/assets/10467960/cd36d022-3559-43b7-9e6a-a2c9ae753b9d">

### Environment

- Operating System: 13.4.1 (c) (22F770820d) on M2
- Python version: Python 3.11.4
- Software versions:
  - Briefcase: 0..3.15
  - Toga: 0.3.2
 
Package            Version   Editable project location
------------------ --------- ------------------------------------
arrow              1.2.3
binaryornot        0.4.4
briefcase          0.3.15
build              0.10.0
certifi            2023.7.22
chardet            5.1.0
charset-normalizer 3.2.0
click              8.1.6
cookiecutter       2.2.3
dmgbuild           1.6.1
ds-store           1.3.1
gitdb              4.0.10
GitPython          3.1.32
idna               3.4
iniconfig          2.0.0
Jinja2             3.1.2
mac-alias          2.2.2
markdown-it-py     3.0.0
MarkupSafe         2.1.3
mdurl              0.1.2
packaging          23.1
pip                23.2.1
platformdirs       3.10.0
pluggy             1.2.0
psutil             5.9.5
Pygments           2.15.1
pyproject_hooks    1.0.0
pytest             7.4.0
python-dateutil    2.8.2
python-slugify     8.0.1
PyYAML             6.0.1
requests           2.31.0
rich               13.5.0
rubicon-objc       0.4.6
setuptools         67.6.1
six                1.16.0
smmap              5.0.0
std-nslog          1.0.3
text-unidecode     1.3
toga-cocoa         0.3.1
toga-core          0.3.1
(togasample         0.0.0     /Users/alexrjs/Sources/py/togasample) -> pip install -e .
tomli_w            1.0.0
travertino         0.2.0
urllib3            2.0.4
wheel              0.41.0

### Logs

```

```
[briefcase.2023_07_29-21_59_21.dev.log](https://github.com/beeware/briefcase/files/12207916/briefcase.2023_07_29-21_59_21.dev.log)
[briefcase.2023_07_29-21_56_42.dev.log](https://github.com/beeware/briefcase/files/12207917/briefcase.2023_07_29-21_56_42.dev.log)
[briefcase.2023_07_29-21_56_06.dev.log](https://github.com/beeware/briefcase/files/12207918/briefcase.2023_07_29-21_56_06.dev.log)

**Comment by freakboy3742** [comment] 2023-07-30 03:15
I think this is a case "Doctor, it hurts when I hold my arm like this!" "Then don't hold your arm like that!".

Briefcase apps aren't installable modules. I'm actually a little surprised running `pip -e .` on a briefcase project works *at all* - we're not doing anything that would facilitate that. I'm guessing recent changes in the packaging ecosystem mean that as long as you've got a pyproject.toml, PEP621 metadata kicks in, and your project is inherently installable because Briefcase conforms to a couple of Python ecosystem norms (like using a `src` directory for sources).

Unfortunately, when you install the app like this using `pip`, you *don't* get some of the application metadata that Briefcase generates, and Toga needs to start, such as the formal name, app ID and version. You can manually modify your Toga mainline to pass in a formal name and app ID (i.e. change the main() method to `return MyApp("My Application", "com.example.myapp")`), which will allow the app to start; but this might have some other unintended consequences down the road. You might also be able to alter some of Briefcase's default metadata to their PEP621 equivalents - as of Briefcase 0.3.15, those values will be read and used by Briefcase if they are provided.

Installing with pip *also* adds the app to your PYTHONPATH - which means that subsequent executions of `briefcase dev` get confused over which version of the app is being used.

Ultimately, what is really needed is a clear set of instructions for how to run a briefcase app in debug mode - and possibly a VSCode extension (and extensions for other common IDEs) that does "briefcase dev". The tl;dr is that you need to set the runtime PYTHONPATH to include the directories mentioned in `sources`, and remove the project home directory. 

I'm going to close this ticket on the basis that it's not a bug - it's a side effect of off-label usage. I've opened #1393 to track adding documentation for IDE configuration.

**Closed by freakboy3742** 2023-07-30 03:15 UTC
Labels: bug

**Comment by alexrjs** [comment] 2023-07-30 05:46
> I think this is a case "Doctor, it hurts when I hold my arm like this!" "Then don't hold your arm like that!".
> 
> 
> 
> Briefcase apps aren't installable modules. I'm actually a little surprised running `pip -e .` on a briefcase project works *at all* - we're not doing anything that would facilitate that. I'm guessing recent changes in the packaging ecosystem mean that as long as you've got a pyproject.toml, PEP621 metadata kicks in, and your project is inherently installable because Briefcase conforms to a couple of Python ecosystem norms (like using a `src` directory for sources).
> 
> 
> 
> Unfortunately, when you install the app like this using `pip`, you *don't* get some of the application metadata that Briefcase generates, and Toga needs to start, such as the formal name, app ID and version. You can manually modify your Toga mainline to pass in a formal name and app ID (i.e. change the main() method to `return MyApp("My Application", "com.example.myapp")`), which will allow the app to start; but this might have some other unintended consequences down the road. You might also be able to alter some of Briefcase's default metadata to their PEP621 equivalents - as of Briefcase 0.3.15, those values will be read and used by Briefcase if they are provided.
> 
> 
> 
> Installing with pip *also* adds the app to your PYTHONPATH - which means that subsequent executions of `briefcase dev` get confused over which version of the app is being used.
> 
> 
> 
> Ultimately, what is really needed is a clear set of instructions for how to run a briefcase app in debug mode - and possibly a VSCode extension (and extensions for other common IDEs) that does "briefcase dev". The tl;dr is that you need to set the runtime PYTHONPATH to include the directories mentioned in `sources`, and remove the project home directory. 
> 
> 
> 
> I'm going to close this ticket on the basis that it's not a bug - it's a side effect of off-label usage. I've opened #1393 to track adding documentation for IDE configuration.

I get your point... IMHO, this decision is a little uncommon, cause then (almost) all who want to use Toga, with a modern IDE setup, will jump off. I did my share of low level debugging in the 80 & 90, but I like to use modern IDE's like PyCharm and VSCode. So I'll stick to customtkinter for the time being. 

Don't get me wrong I think you doing a great work, exactly what Python needs, and I'll keep an eye on the project, but I will stick to a guideline an old mentor gave me when I started in the 80... "Do the expected thing, not the unexpected... That avoids a lot of hazzle and friction..."

Good luck and success...
