### ISSUE TITLE
briefcase build - should allow post-process to codesign app binary

### ISSUE THREAD

**Issue by genkiyooka** [beeware/briefcase#626] opened 2021-10-17 05:28 UTC
Under Big Sur, the application binary created by cookiecutter is unsigned (intentionally).

The binary cannot be executed by a user under Big Sur until the binary is codesigned.

Recommend adding a postprocess phase that would check for the existence of an environment variable (say BRIEFCASE_CODESIGN_IDENTITY) containing the developer's codesigning identity and, if present, run codesign -f -s "$BRIEFCASE_CODESIGN_IDENTITY" <<path_to_app_bundle>>

If the BRIEFCASE_CODESIGN_IDENTITY is not set, emit some kind of warning message that the application bundle will contain an unsigned binary and may not run on modern versions of macOS.

Currently I have a shell command that runs briefcase build and then executes the codesign.

This also will prevent new users of the tutorial from spending time trying to figure out why the application bundle is invalid (will not launch).

**Comment by freakboy3742** [comment] 2021-10-17 23:27
Thanks for the report; this is definitely something we need to address.

We already have code signing functionality; it's applied as part of the `briefcase package` step. We also have `adhoc` signing, which doesn't require an explicit code sign identity.

It sounds like it might make sense to move the code signing step into the `build` command.

**Comment by freakboy3742** [comment] 2022-03-01 01:11
Further clarification on this: the problem appears to be specific to M1 hardware. My testing was on an M1 Mac mini, with Monterey 12.1). The same test on an Intel MacBook Pro worked without difficulty.

Adhoc signing is sufficient to make the executable runnable locally (`briefcase package -p app --adhoc-sign`), but won't work for distribution purposes.

**Comment by freakboy3742** [comment] 2022-03-25 05:18
Closing this as a duplicate of #664; adding adhoc signing as part of the build process on macOS will be sufficient to address the problem described here.

**Closed by freakboy3742** 2022-03-25 05:18 UTC
Labels: enhancement, up-for-grabs, macOS
