### ISSUE TITLE
Briefcase `create` and `build` doesn't package the locally installed version of toga

### ISSUE THREAD

**Issue by proneon267** [beeware/briefcase#1415] opened 2023-08-24 08:56 UTC
### Describe the bug

Briefcase `create`, `build` and `run` doesn't package the locally installed version of toga. 

This is becomes an issue when I want to test an app in packaged form that uses a locally installed version of toga(having modifications that are not yet merged in the toga main branch). 

This is especially problematic when testing modified versions of toga on Android, since I cannot just do `briefcase dev` for android.

### Steps to reproduce

1. Modify a git clone repo of toga locally.
2. Install the locally modified toga repo, example:
```
pip install -e ./core[dev] -e ./dummy -e ./winforms

```

3. Create an example toga app that use the newly modified API from the locally installed toga repo.
4. Doing `briefcase dev` will work just fine. But, doing `briefcase run` will give an error that the invoked new APIs were not found.
5. Similarly, doing `briefcase create android` and `briefcase build android`, the resultant apk when installed, will crash.

These errors are caused as briefcase doesn't use the locally installed toga.

### Expected behavior

Briefcase should give an option to choose the locally modified toga version with the app.

### Environment

- Operating System: Any
- Python version: 3.10
- Software versions:
  - Briefcase: 0.3.15
  - Toga: Local version
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment] 2023-08-24 09:07
This is briefcase working as intended.

Briefcase doesn't pay any attention to your local environment. If you install a package into your local environment, it won't be installed into your packaged app.

The only things that will be installed into your app are the packages that are listed in the `requires` setting of your `pyproject.toml`. 

If you want to use a local checkout of a library in your packaged app... then your `requires` setting needs to reflect this. You can see an example of this in Toga's examples folder - those examples all reference the local Toga sources, rather than a stable release version.

**Closed** 2023-08-24 09:07 UTC
Labels: bug

**Comment by proneon267** [comment] 2023-08-24 09:31
Thanks. I had forgotten about `requires`:)
