### ISSUE TITLE
Android build incompatible with system-installed cmake

### ISSUE THREAD

**Issue by kitlycol** [beeware/briefcase#615] opened 2021-09-03 09:41 UTC
failed with build android tutorial app

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelDebug'.
> exception while building Json Expected json generation to create '..armeabi-v7a/android_gradle_build.json' but it didn't

same problems to this issues.
[https://github.com/beeware/beeware/issues/120](https://github.com/beeware/beeware/issues/120)

**Comment by IlVice26** [comment] 2021-09-06 09:52
I get this problem too,
I also attach other information that came up during the briefcase build android command

```
> Task :app:generateJsonModelDebug FAILED
debug|armeabi-v7a :CMake Warning (dev) in CMakeLists.txt:
debug|armeabi-v7a :  No project() command is present.  The top-level CMakeLists.txt file must
debug|armeabi-v7a :  contain a literal, direct call to the project() command.  Add a line of
debug|armeabi-v7a :  code such as
debug|armeabi-v7a :    project(ProjectName)
debug|armeabi-v7a :  near the top of the file, but after cmake_minimum_required().
debug|armeabi-v7a :  CMake is pretending there is a "project(Project)" command on the first
debug|armeabi-v7a :  line.
debug|armeabi-v7a :This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by IlVice26** [comment] 2021-09-06 14:23
After a whole day I managed to figure out how to fix the problem... I removed the installed version of cmake from the system and let briefcase install its version.
Briefcase downloads 3.6.. while the one I found on Ubuntu 20.04 is 3.16.

**Comment by freakboy3742** [comment] 2021-09-06 22:52
@IlVice26 Looks like you've confirmed the hypothesis I proposed in beeware/beeware#120 - it's a system-installed cmake that is the problem. 

As you've discovered, the short term fix is the disable/remove the system installed version of cmake. However, that's an undesirable permanent solution. briefcase should be able to co-exist with anything pre-existing on the system. 

The [Android installation docs](https://developer.android.com/studio/projects/install-ndk) suggest that you can add:

```
cmake.dir = "path-to-cmake"
```

to a `local.properties` in the root of the project. I've also seen some references to a `CMAKE_MAKE_PROGRAM` variable. 

I'll keep looking, but if you're able to find a way to configure the Android project so that it finds the version of cmake installed by BeeWare(`~/.briefcase/tools/android_sdk/cmake/3.6.4111459/bin`), I can roll that into briefcase as a default.

**Comment by freakboy3742** [comment] 2021-09-06 23:12
I've been able to reproduce this locally; if you add
```
cmake.dir=/Users/rkm/.briefcase/tools/android_sdk/cmake/3.6.4111459
```
to a `local.properties` file `android/gradle/<your project>`, (the syntax proposed by the Android docs is incorrect), the build will succeed. The next question is to work out how to derive the 3.6.4111459 magic number...

**Comment by main1015** [comment] 2021-09-08 02:24
@freakboy3742 
I didn't find the cmake' 3.6.4111459 'version you said and I was using the' 3.6.3'version but the results were the same.

My directory structure
![image](https://user-images.githubusercontent.com/3272281/132436139-3c02dd94-bd29-41df-98af-e715a02735b2.png)

Results
![image](https://user-images.githubusercontent.com/3272281/132436178-0cbb72c9-db56-4b7c-82b7-04c4bc67083f.png)

**Comment by freakboy3742** [comment] 2021-09-08 04:47
I can't (or shouldn't need to) provide a cmake download address - the download process is managed by the Android toolchain, because it's an Android-specific patched version of cmake. The underlying problem here is that you *have* download a version of cmake, and it's conflicting.

Can you confirm that if you change that path definition to a path that *doesn't* exist, you get an error that indicates cmake.dir was read, but the value was invalid? For example, I get:
```
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: Could not get version from cmake.dir path '/Users/rkm/.briefcase/tools/android_sdk/cmake/3.6.4111459-bad'.
```

**Comment by main1015** [comment] 2021-09-08 05:08
@freakboy3742 
I am manually under the compiled version in this directory

**Comment by freakboy3742** [comment] 2021-09-08 05:10
What was that answer in response to? It doesn't seem to have anything to do with the diagnostic test I asked you to perform.

**Comment by main1015** [comment] 2021-09-08 05:16
I mean I manually downloaded cmake, and configured this path in effect.If I modify a wrong path it will prompt camke can t find then show that my path is effective

**Comment by freakboy3742** [comment] 2021-09-08 05:18
I have already said this, but I cannot emphasise it enough - **do not manually download cmake**. The Android SDK manager will automatically download cmake. It needs to download cmake on it's own. You need the *Android* version of cmake, managed by the Android developer toolchain.

**Comment by main1015** [comment] 2021-09-08 05:31
@freakboy3742
Thanks it should be I understand the error thinking it was ok to manually download a cmake version and here is actually a cmake. that needs an Android sdk download after I downloaded it, now I can compile it normally, thank you very much

**Comment by zili55** [comment] 2021-09-17 08:27
My `android_sdk` installation by briefcase missed cmake and with my system cmake throws error too.The required cmake can be installed manually  via `./sdkmanager --install "cmake;3.6.4111459"` from `~/.briefcase/tools/android_sdk/tools/bin`.

**Comment by freakboy3742** [comment] 2021-09-26 03:00
As best as I can make out, the template patch provided by @zili55 has addressed this problem. Closing; if anyone continues to see this issue, please let us know.

**Closed by freakboy3742** 2021-09-26 03:00 UTC
Labels: bug, up-for-grabs, android
